/*
  Learn module — "Biologie 5. Klasse"
  Themen: Biotechnologie, Mikrobiologie, Mikroorganismen (Prokaryoten/Eukaryoten),
          Organsysteme & Stoffwechsel, Bestandteile der Nahrung, Ernährung im Tierreich.

  Registers in window.LEARN_REGISTRY so index.html can find it.

  Data types:
    flashcards    : {id, term, def, ex?}
    quiz          : {id, q, opts, correct, expl}   // correct = index into opts
    openQuestions : {id, q, modelAnswer, keyPoints:[]}
*/
(window.LEARN_REGISTRY=window.LEARN_REGISTRY||[]).push({
id:"bio5-de",
name:"Biologie 5. Klasse",
subject:"Biologie",
icon:"🔬",
flashcards:[
{id:"fc-bio-biotechnologie",term:"Biotechnologie",def:"Nutzung von Lebewesen – vor allem Mikroorganismen – zur Herstellung von Produkten oder zur Lösung technischer Probleme. Beispiele: Insulin, Antibiotika, Brot, Bier, Joghurt."},
{id:"fc-bio-gaerung",term:"Gärung",def:"Anaerober (sauerstofffreier) Abbau von Zucker durch Mikroorganismen. Alkoholische Gärung: Hefen → Ethanol + CO₂ (Brot, Bier, Wein). Milchsäurefärung: Milchsäurebakterien → Milchsäure (Joghurt, Käse)."},
{id:"fc-bio-prokaryot",term:"Prokaryoten",def:"Einzeller OHNE echten, membranumhüllten Zellkern – die DNA liegt frei im Zellplasma. Einfacher Zellaufbau. Beispiel: Bakterien."},
{id:"fc-bio-eukaryot",term:"Eukaryoten",def:"Zellen MIT echtem Zellkern, der von einer Doppelmembran umgeben ist. Besitzen weitere Organellen (z. B. Mitochondrien). Dazu zählen: Pflanzen, Tiere, Pilze, Protisten."},
{id:"fc-bio-autotroph",term:"Autotroph",def:"Organismen, die aus anorganischen Stoffen (CO₂, Wasser) mit Hilfe von Lichtenergie organische Verbindungen selbst herstellen können (Photosynthese). Beispiel: Grüne Pflanzen – Produzenten."},
{id:"fc-bio-heterotroph",term:"Heterotroph",def:"Organismen, die auf die Aufnahme fertiger organischer Nahrung angewiesen sind. Beispiel: Alle Tiere, Pilze, die meisten Bakterien – Konsumenten."},
{id:"fc-bio-kohlenhydrate",term:"Kohlenhydrate",def:"Einfachzucker (Monosaccharide): Glukose. Zweifachzucker (Disaccharide): Saccharose (Haushaltszucker). Vielfachzucker (Polysaccharide): Stärke, Glykogen. Hauptenergielieferant des Körpers."},
{id:"fc-bio-fette",term:"Fette",def:"Aufgebaut aus Glycerin + 3 Fettsäuren (Kondensationsreaktion). Funktion: Energiereserve, Wärmedämmung, Lösungsmittel für fettlösliche Vitamine."},
{id:"fc-bio-proteine",term:"Proteine (Eiweiße)",def:"Aufgebaut aus Aminosäuren, die zu langen Ketten verknüpft sind. Funktionen: Enzyme (Katalyse), Strukturproteine (Muskel, Kollagen), Hormone (Insulin), Antikörper (Immunabwehr)."},
{id:"fc-bio-vitamine",term:"Vitamine",def:"Lebenswichtige organische Wirkstoffe, die der Körper nicht selbst herstellen kann. Fettlöslich (speicherbar): A, D, E, K. Wasserlöslich (nicht speicherbar): B-Gruppe, C."},
{id:"fc-bio-mineralstoffe",term:"Mineralstoffe & Spurenelemente",def:"Anorganische Nährstoffe. Calcium (Knochen/Zähne), Eisen (Blut/Hämoglobin), Kalium/Natrium (Nerven), Magnesium (Enzyme), Jod (Schilddrüse). Spurenelemente: nur in kleinsten Mengen nötig (z. B. Zink, Selen)."},
{id:"fc-bio-duenndarm",term:"Dünndarm",def:"3 Abschnitte; 3–6 m lang; zwischen Magen und Dickdarm; stark gefaltet. Funktion: Zerlegung der Nahrung durch Enzyme, Aufnahme (Resorption) von Nährstoffen über Darmzotten. Erhält Verdauungssäfte von Leber/Galle und Bauchspeicheldrüse."},
{id:"fc-bio-dickdarm",term:"Dickdarm",def:"Entzieht dem Nahrungsbrei Wasser – der Brei wird eingedickt. Weiterleitung zum Enddarm. Kein nennenswerter Nährstoffabbau mehr."},
{id:"fc-bio-herbivor",term:"Herbivore / Carnivore / Omnivore",def:"Herbivore = Pflanzenfresser (Schneide- und Mahlzähne). Carnivore = Fleischfresser (Reiß- und Fangzähne). Omnivore = Allesfresser (alle Zahntypen). Anpassungen auch in Verdauung und Verhalten."},
{id:"fc-bio-parasit",term:"Parasit vs. Prädator",def:"Parasit: lebt dauerhaft auf/in einem Wirt, entzieht ihm Nährstoffe ohne ihn sofort zu töten (z. B. Zecke). Prädator: tötet und frisst seine Beute aktiv (z. B. Wolf). Parasit braucht den Wirt lebend."}
],
quiz:[
// ── Biotechnologie ────────────────────────────────────────────
{id:"qb1",q:"Welcher Mikroorganismus ist für die alkoholische Gärung (Bier, Wein, Brot) verantwortlich?",
opts:["Milchsäurebakterien","Hefepilze","Schimmelpilze","E. coli"],correct:1,
expl:"Hefepilze (z. B. Saccharomyces cerevisiae) bauen Zucker anaerob ab und produzieren dabei Ethanol und CO₂ – das nennt man alkoholische Gärung."},
{id:"qb2",q:"Was entsteht bei der alkoholischen Gärung?",
opts:["Milchsäure + Wasser","Ethanol + CO₂","Essigsäure + O₂","Glukose + Stärke"],correct:1,
expl:"Bei der alkoholischen Gärung setzen Hefen Zucker (Glukose) in Ethanol (Alkohol) und Kohlendioxid (CO₂) um."},
{id:"qb3",q:"Durch welche Mikroorganismen wird Milch zu Joghurt?",
opts:["Milchsäurebakterien","Hefepilze","Schimmelpilze","Viren"],correct:0,
expl:"Milchsäurebakterien vergären Milchzucker (Laktose) zu Milchsäure – dadurch wird die Milch sauer und dickflüssig: Joghurt entsteht."},
{id:"qb4",q:"Welches Medikament wird heute gentechnisch durch Bakterien hergestellt und dient der Diabetesbehandlung?",
opts:["Penicillin","Insulin","Amylase","Laktase"],correct:1,
expl:"Insulin wird heute mithilfe gentechnisch veränderter Bakterien (E. coli) hergestellt. Das Insulin-Gen wurde in das Bakteriengenom eingebaut."},
{id:"qb5",q:"Was versteht man unter Biotechnologie?",
opts:["Herstellung chemischer Stoffe ohne Organismen","Züchtung von Zierpflanzen","Nutzung von Lebewesen zur Herstellung von Produkten","Einsatz von Maschinen in der Landwirtschaft"],correct:2,
expl:"Biotechnologie bezeichnet die gezielte Nutzung von Lebewesen – vor allem Mikroorganismen – zur Herstellung von Produkten (Insulin, Antibiotika, Lebensmittel) oder zur Lösung technischer Probleme."},
// ── Mikrobiologie / Mikroorganismen ───────────────────────────
{id:"qm1",q:"Was ist der wesentliche Unterschied zwischen Prokaryoten und Eukaryoten?",
opts:["Prokaryoten sind immer größer als Eukaryoten","Prokaryoten haben keinen echten Zellkern – die DNA liegt frei im Plasma","Eukaryoten haben keine Zellmembran","Prokaryoten haben immer eine Zellwand aus Chitin"],correct:1,
expl:"Prokaryoten (z. B. Bakterien) haben keinen membranumhüllten Zellkern – ihre DNA liegt frei im Zellplasma. Eukaryoten besitzen einen echten Zellkern mit Doppelmembran."},
{id:"qm2",q:"Welche der folgenden Gruppen sind Prokaryoten?",
opts:["Pflanzen","Pilze","Bakterien","Tiere"],correct:2,
expl:"Bakterien sind Prokaryoten – die einzige große Gruppe mit prokaryotischem Zellbau. Pflanzen, Tiere und Pilze sind Eukaryoten."},
{id:"qm3",q:"Welchen Zellbestandteil haben Bakterien NICHT?",
opts:["Zellmembran","Ribosomen","Membranumhüllter Zellkern","Zellwand"],correct:2,
expl:"Bakterien (Prokaryoten) haben keinen membranumhüllten Zellkern. Ihre DNA liegt frei im Zytoplasma. Zellmembran, Ribosomen und Zellwand sind hingegen vorhanden."},
{id:"qm4",q:"Womit können Bakterien Erkrankungen beim Menschen verursachen?",
opts:["Durch Photosynthese","Durch Produktion von Giftstoffen (Toxinen)","Durch Bildung von Stärke","Durch Aufnahme von Sauerstoff"],correct:1,
expl:"Krankheitserregende Bakterien (Pathogene) schädigen den Wirt vor allem durch die Produktion von Giftstoffen (Toxinen), z. B. Tetanustoxin oder Botulinumtoxin."},
{id:"qm5",q:"Welche Aussage über Eukaryoten ist richtig?",
opts:["Sie haben keinen Zellkern","Nur Tiere sind Eukaryoten","Pflanzen, Tiere und Pilze sind Eukaryoten","Sie haben keine Mitochondrien"],correct:2,
expl:"Eukaryoten sind alle Organismen mit echtem, membranumhülltem Zellkern. Dazu gehören Pflanzen, Tiere, Pilze und Protisten."},
// ── Organsysteme & Stoffwechsel ───────────────────────────────
{id:"qs1",q:"Woraus werden Fette im Körper aufgebaut?",
opts:["Aminosäuren + Glukose","Glycerin + Fettsäuren","Stärke + Wasser","Glukose + Sauerstoff"],correct:1,
expl:"Fette entstehen durch die Verbindung von einem Glycerinmolekül mit drei Fettsäuren (Kondensationsreaktion). Diese Verbindung heißt Triglycerid."},
{id:"qs2",q:"Was bedeutet autotrophe Ernährungsweise?",
opts:["Tiere fressen andere Tiere","Organismen bauen organische Stoffe aus anorganischen Stoffen selbst auf","Organismen nehmen fertige organische Nahrung auf","Pilze zersetzen abgestorbenes Material"],correct:1,
expl:"Autotrophe Organismen (z. B. Pflanzen) können mit Sonnenenergie aus CO₂ und Wasser organische Verbindungen (Zucker) selbst aufbauen – Photosynthese."},
{id:"qs3",q:"Was ist richtig über heterotrophe Organismen?",
opts:["Sie stellen alle Nährstoffe selbst her","Sie sind auf vorgefertigte organische Nahrung angewiesen","Nur Pilze sind heterotroph","Sie betreiben Photosynthese"],correct:1,
expl:"Heterotrophe (z. B. Tiere, Pilze) können keine organischen Stoffe aus anorganischen herstellen und sind daher auf fertige Nahrung angewiesen."},
{id:"qs4",q:"Woraus bestehen Proteine (Eiweiße)?",
opts:["Fettsäuren","Glukosemoleküle","Aminosäuren","Glycerin"],correct:2,
expl:"Proteine sind lange Ketten aus Aminosäuren, die durch Peptidbindungen verknüpft sind. Es gibt 20 verschiedene proteinogene Aminosäuren."},
{id:"qs5",q:"Welche Funktion haben Enzyme im Körper?",
opts:["Energiespeicherung","Beschleunigung chemischer Reaktionen (Biokatalyse)","Wärmedämmung","Sauerstofftransport im Blut"],correct:1,
expl:"Enzyme sind Biokatalysatoren: Sie beschleunigen chemische Reaktionen im Körper, ohne selbst verbraucht zu werden. Verdauungsenzyme spalten z. B. Nährstoffe auf."},
// ── Bestandteile der Nahrung ──────────────────────────────────
{id:"qn1",q:"Welche Vitamine sind fettlöslich (und können im Körper gespeichert werden)?",
opts:["B-Gruppe und C","A, D, E und K","Nur Vitamin C","B1 und B12"],correct:1,
expl:"Fettlösliche Vitamine (A, D, E, K) können in Fettgewebe und Leber gespeichert werden. Wasserlösliche Vitamine (B-Gruppe, C) werden über den Urin ausgeschieden."},
{id:"qn2",q:"Welcher Mineralstoff ist besonders wichtig für die Blutbildung (Hämoglobin)?",
opts:["Calcium","Kalium","Eisen","Magnesium"],correct:2,
expl:"Eisen ist ein zentraler Bestandteil des Hämoglobins (roter Blutfarbstoff). Eisenmangel führt zu Blutarmut (Anämie)."},
{id:"qn3",q:"Zu welcher Kohlenhydrat-Gruppe gehört Stärke?",
opts:["Monosaccharide","Disaccharide","Polysaccharide","Fettsäuren"],correct:2,
expl:"Stärke ist ein Polysaccharid (Vielfachzucker) – ein langes Kettenmolekül aus vielen Glukoseeinheiten. Monosaccharid = Glukose; Disaccharid = Saccharose (Haushaltszucker)."},
// ── Verdauungssystem ──────────────────────────────────────────
{id:"qv1",q:"In welchem Abschnitt des Verdauungstrakts werden die meisten Nährstoffe resorbiert?",
opts:["Magen","Dünndarm","Dickdarm","Speiseröhre"],correct:1,
expl:"Im Dünndarm (3–6 m lang) werden die durch Enzyme aufgespaltenen Nährstoffe über Darmzotten ins Blut und die Lymphe aufgenommen (Resorption)."},
{id:"qv2",q:"Was ist die Hauptaufgabe des Dickdarms?",
opts:["Nährstoffresorption","Wasserentzug und Eindickung des Stuhls","Produktion von Verdauungsenzymen","Fettemulgierung mit Galle"],correct:1,
expl:"Der Dickdarm entzieht dem unverdaulichen Rest Wasser und formt so den Stuhl. Er resorbiert keine nennenswerten Mengen an Nährstoffen mehr."},
{id:"qv3",q:"Welches Organ produziert die Galle zur Fettemulgierung?",
opts:["Bauchspeicheldrüse","Magen","Leber","Dünndarm"],correct:2,
expl:"Die Leber (größte Drüse des Körpers, ca. 1,5 kg) produziert Galle. Diese wird in der Gallenblase gespeichert und in den Zwölffingerdarm abgegeben."},
{id:"qv4",q:"Wie lang ist der menschliche Dünndarm ungefähr?",
opts:["50 cm","1–2 m","3–6 m","10 m"],correct:2,
expl:"Der Dünndarm ist 3–6 m lang und hat durch Darmzotten und Mikrozotten eine enorm vergrößerte Oberfläche (ca. 200 m²), was eine effiziente Nährstoffresorption ermöglicht."},
// ── Ernährung im Tierreich ────────────────────────────────────
{id:"qe1",q:"Wie nennt man einen reinen Pflanzenfresser?",
opts:["Carnivore","Omnivore","Herbivore","Parasit"],correct:2,
expl:"Herbivore (lat. herba = Pflanze) sind reine Pflanzenfresser. Sie haben speziell angepasste Zähne (Schneide- und Mahlzähne) und einen langen Verdauungstrakt."},
{id:"qe2",q:"Welches Tier ist ein bekannter Nahrungsspezialist, der fast ausschließlich Eukalyptusblätter frisst?",
opts:["Ameisenbär","Koalabär","Zecke","Schmetterling"],correct:1,
expl:"Der Koalabär ist auf Eukalyptusblätter spezialisiert. Diese sind für die meisten Tiere giftig – der Koala hat spezielle Enzyme, um die Giftstoffe abzubauen."},
{id:"qe3",q:"Was unterscheidet einen Parasiten von einem Prädator?",
opts:["Parasiten sind immer kleiner als ihr Wirt","Parasiten töten den Wirt sofort","Parasiten leben dauerhaft auf Kosten des Wirts, ohne ihn sofort zu töten","Parasiten fressen nur Pflanzen"],correct:2,
expl:"Ein Parasit (z. B. Zecke, Bandwurm) lebt dauerhaft auf/in seinem Wirt und entzieht ihm Nährstoffe, ohne ihn sofort zu töten. Ein Prädator tötet und frisst seine Beute aktiv."}
],
openQuestions:[
{id:"oq1",
q:"Erkläre den Unterschied zwischen Prokaryoten und Eukaryoten. Nenne je ein Beispiel.",
modelAnswer:"Prokaryoten (z. B. Bakterien) haben keinen echten, membranumhüllten Zellkern – ihre DNA liegt frei im Zellplasma. Ihr Zellbau ist einfach. Eukaryoten (z. B. Pflanzen, Tiere, Pilze) besitzen dagegen einen echten Zellkern, der von einer Doppelmembran umgeben ist, sowie weitere Zellorganellen wie Mitochondrien.",
keyPoints:["Prokaryoten: kein echter Zellkern, DNA liegt frei im Plasma","Beispiel Prokaryot: Bakterien","Eukaryoten: echter membranumhüllter Zellkern","Beispiel Eukaryot: Pflanze, Tier oder Pilz"]},
{id:"oq2",
q:"Was versteht man unter Biotechnologie? Nenne drei konkrete Anwendungsbeispiele aus dem Alltag.",
modelAnswer:"Biotechnologie bezeichnet die gezielte Nutzung von Lebewesen – vor allem Mikroorganismen – zur Herstellung von Produkten oder zur Lösung technischer Probleme. Beispiele: (1) Brot und Bier durch alkoholische Gärung mit Hefen, (2) Joghurt und Käse durch Milchsäurebakterien, (3) Insulin für Diabetiker durch gentechnisch veränderte Bakterien.",
keyPoints:["Definition: Nutzung von Lebewesen/Mikroorganismen zur Produktherstellung","Brot oder Bier (Hefen/Gärung)","Joghurt oder Käse (Milchsäurebakterien)","Insulin oder Antibiotika (Gentechnik)"]},
{id:"oq3",
q:"Beschreibe den Weg der Nahrung durch das Verdauungssystem vom Mund bis zum Dickdarm. Nenne mindestens 5 Stationen.",
modelAnswer:"1. Mund: Zerkleinern durch Zähne, Einspeicheln (Speichelamylase beginnt Stärkeabbau). 2. Speiseröhre: Transport durch Muskelkontraktionen. 3. Magen: Magensaure und Enzyme bauen Proteine ab; Schleimhaut schützt den Magen. 4. Dünndarm: Galle (aus Leber/Gallenblase) emulgiert Fette; Enzyme der Bauchspeicheldrüse spalten Nährstoffe auf; Nährstoffe werden über Darmzotten resorbiert. 5. Dickdarm: Wasser wird entzogen, Stuhl wird gebildet.",
keyPoints:["Mund: Zähne + Speichel","Speiseröhre: Transport","Magen: Magensaure + Proteinverdauung","Leber/Galle + Bauchspeicheldrüse im Dünndarm","Dünndarm: Resorption über Darmzotten","Dickdarm: Wasserentzug"]},
{id:"oq4",
q:"Was ist der Unterschied zwischen autotropher und heterotropher Ernährung? Gib jeweils ein Beispiel.",
modelAnswer:"Autotrophe Organismen können aus anorganischen Stoffen (CO₂, Wasser) mit Hilfe von Lichtenergie organische Verbindungen selbst aufbauen (Photosynthese). Beispiel: Grüne Pflanzen. Heterotrophe Organismen können das nicht und sind auf die Aufnahme fertiger organischer Nahrung angewiesen. Beispiel: Alle Tiere, einschließlich des Menschen.",
keyPoints:["autotroph: organische Stoffe aus anorganischen selbst aufbauen","Photosynthese bei Pflanzen als Beispiel","heterotroph: auf fertige organische Nahrung angewiesen","Beispiel heterotroph: Tier oder Mensch"]},
{id:"oq5",
q:"Erkläre die Funktion von Proteinen im menschlichen Körper und erkläre, woraus sie bestehen.",
modelAnswer:"Proteine bestehen aus Aminosäuren, die zu langen Ketten verknüpft sind. Sie erfüllen im Körper viele Aufgaben: Als Enzyme beschleunigen sie chemische Reaktionen. Als Strukturproteine (z. B. Kollagen, Aktin) geben sie Zellen und Gewebe Halt. Insulin ist ein Proteinhormon. Antikörper bestehen ebenfalls aus Proteinen und schützen uns vor Krankheitserregern.",
keyPoints:["Baustein: Aminosäuren","Enzyme (Katalyse chemischer Reaktionen)","Strukturproteine (Muskel, Bindegewebe)","Hormone (Insulin als Beispiel)","Antikörper (Immunabwehr)"]},
{id:"oq6",
q:"Erkläre den Unterschied zwischen fettlöslichen und wasserlöslichen Vitaminen. Nenne jeweils zwei Beispiele.",
modelAnswer:"Fettlösliche Vitamine (A, D, E, K) werden zusammen mit Nahrungsfetten aufgenommen und können in Fettgewebe und Leber gespeichert werden – eine Überversorgung ist möglich. Wasserlösliche Vitamine (B-Gruppe, C) können nicht im Körper gespeichert werden und müssen regelmäßig aufgenommen werden; überschüssige Mengen werden über den Urin ausgeschieden.",
keyPoints:["fettlöslich: A, D, E, K (mindestens zwei nennen)","fettlöslich: im Körper speicherbar","wasserlöslich: B-Gruppe oder C (mindestens zwei nennen)","wasserlöslich: nicht speicherbar, Ausscheidung über Urin"]},
{id:"oq7",
q:"Warum hat der Dünndarm eine so große Oberfläche und welche Bedeutung hat das für die Verdauung?",
modelAnswer:"Die Oberfläche des Dünndarms wird durch Darmfalten, Darmzotten und Mikrozotten (Bürstensaum) enorm vergrößert – auf insgesamt ca. 200 m². Diese große Oberfläche ermöglicht eine besonders effiziente Aufnahme (Resorption) der verdauten Nährstoffe – Zucker, Aminosäuren und Fettsäuren – ins Blut und die Lymphe. Ohne diese Oberflächenvergrößerung wäre die Nährstoffaufnahme viel zu langsam.",
keyPoints:["Darmzotten und Mikrozotten vergrößern die Oberfläche","ca. 200 m² Gesamtoberfläche","effiziente Resorption von Nährstoffen","Nährstoffe gehen ins Blut / die Lymphe"]},
{id:"oq8",
q:"Erkläre den Begriff Parasitismus anhand eines Beispiels und grenze ihn vom Begriff Prädator ab.",
modelAnswer:"Ein Parasit lebt dauerhaft auf oder in einem Wirt und entnimmt ihm Nährstoffe, ohne ihn sofort zu töten (z. B. Zecke saugt Blut vom Menschen). Der Parasit ist auf das Überleben seines Wirts angewiesen. Ein Prädator (Räuber) hingegen tötet und frisst seine Beute aktiv (z. B. Wolf frisst Reh). Der wesentliche Unterschied: Der Parasit braucht den lebenden Wirt, der Prädator tötet sofort.",
keyPoints:["Parasit lebt auf/in einem Wirt","schadet dem Wirt ohne sofortiges Töten","Beispiel: Zecke, Bandwurm oder ähnlich","Prädator tötet Beute aktiv","Parasit braucht den lebenden Wirt"]}
]
});
