/*
  Learn module — "Epik" (Deutsch 3. Klasse).
  Source: Screenshots in screenshots/Deutsch 3/ (Epik 1/2, Epische Formen 1/2/3, Beispiel 1..5).
  Content is strictly from the textbook; examples only where the perspective /
  Personenrede is unambiguous. IDs are stable — never renumber.

  Registers in window.LEARN_REGISTRY so index.html can find it.

  Data types:
    flashcards : {id, term, def, ex?}
    quiz       : {id, q, opts, correct, expl}   // correct = index into opts
    texts      : {id, author, work, year, kind, choices, correct, text, expl}
                 kind ∈ "perspektive" | "personenrede"
*/
(window.LEARN_REGISTRY=window.LEARN_REGISTRY||[]).push({
id:"epik-de",
name:"Epik – Deutsch 3. Klasse",
subject:"Deutsch",
icon:"📖",
flashcards:[
{id:"fc-epik",term:"Epik",def:"Alle fiktionalen erzählenden Texte. Meist eine durchgängige Handlung, mehr oder weniger frei erfundene (fiktionale) Geschichte. In gebundener Sprache (Versen) oder in ungebundener Sprache (Prosa) verfasst."},
{id:"fc-beschreiben",term:"Beschreiben vs. Erzählen",def:"Beschreiben: das Dargestellte wird genau und detailgetreu ausgeführt, der Handlungsverlauf tritt in den Hintergrund, die Erzählzeit überwiegt gegenüber der erzählten Zeit. Erzählen: die Darstellungen treiben den Handlungsgang (Plot) voran."},
{id:"fc-auktorial",term:"Auktoriale Erzählperspektive",def:"3. Person (Er-/Sie-Form). Ein allwissender Erzähler berichtet und erläutert das Geschehen. Er kann Gedanken der Figuren lesen, darstellen und kommentieren, klärt den/die Leser/in über wichtige Aspekte auf und kann ihn/sie direkt ansprechen."},
{id:"fc-personal",term:"Personale Erzählperspektive",def:"3. Person (Er-/Sie-Form). Keine konkrete Erzählfigur — das Geschehen wird aus Sicht der handelnden Figur(en) dargestellt. Die Erzählfigur ist NICHT allwissend. Der Leser kann das Geschehen aus verschiedenen Blickwinkeln betrachten."},
{id:"fc-neutral",term:"Neutrale Erzählperspektive",def:"3. Person (Er-/Sie-Form). Der Erzähler nimmt die Position eines unsichtbaren Beobachters ein. Er kennt weder Gedanken noch Gefühle der Figuren und mischt sich nicht mit Kommentaren/Wertungen ein. Man spricht auch von der Kameraperspektive."},
{id:"fc-ich",term:"Ich-Erzähler/in",def:"1. Person (Ich-Form). Die Ich-Figur berichtet aus ihrer subjektiven Sicht. Es fehlt eine übergeordnete Erzählinstanz — der Leser ist unmittelbar mit dem Geschehen konfrontiert."},
{id:"fc-erzaehlteZeit",term:"Erzählte Zeit",def:"Der Handlungszeitraum — jener Abschnitt an Tagen, Monaten oder Jahren, der im Text auf wenigen oder ein paar hundert Seiten dargestellt wird."},
{id:"fc-erzaehlzeit",term:"Erzählzeit",def:"Die Lesezeit — jene Zeit, welche die Erzählerin/der Erzähler zum Erzählen bzw. die Leserin/der Leser zum Lesen der Geschichte benötigt."},
{id:"fc-zeitstrukturen",term:"Zeitdeckend / zeitraffend / zeitdehnend",def:"zeitdeckend: Erzählzeit = erzählte Zeit. zeitraffend: Erzählzeit kleiner als erzählte Zeit. zeitdehnend: Erzählzeit größer als erzählte Zeit."},
{id:"fc-erzaehlerbericht",term:"Erzählerbericht",def:"Alle Aussagen, die NICHT von einer Figur, sondern vom Erzähler getätigt werden."},
{id:"fc-direkteRede",term:"Direkte Rede",def:"Die Äußerung einer Person wird wörtlich wiedergegeben (mit Anführungszeichen). Die Person tritt in den Vordergrund. Wirkt unmittelbar anschaulich; indirekt charakterisierend.",ex:"Hanna fragte sich: \u201eSoll ich wirklich zu dieser Verabredung gehen?\u201c"},
{id:"fc-indirekteRede",term:"Indirekte Rede",def:"Äußerungen werden durch den Erzähler wiedergegeben (typisch Konjunktiv). Der Erzähler tritt als Vermittler auf — die indirekte Rede schafft Distanz.",ex:"Hanna fragte sich, ob sie wirklich zu der Verabredung gehen solle."},
{id:"fc-erlebteRede",term:"Erlebte Rede",def:"(Zumeist) Gedanken werden aus der Sicht der betroffenen Person wiedergegeben, aber in der 3. Person — also formal von einem Erzähler.",ex:"Sollte sie wirklich zu der Verabredung gehen?"},
{id:"fc-innererMonolog",term:"Innerer Monolog",def:"Das \u201eSelbstgespräch\u201c einer Person wird wiedergegeben. Der Erzähler tritt völlig in den Hintergrund. Steht immer in der 1. Person. Im Unterschied zum Bewusstseinsstrom reflektierender. Regt zum Mitfühlen / zur Identifikation an.",ex:"Soll ich wirklich zu der Verabredung gehen? Ich kenne den Typen doch gar nicht. Ach, was soll schon passieren?"},
{id:"fc-bewusstseinsstrom",term:"Bewusstseinsstrom (Stream of Consciousness)",def:"Gedanken, Gefühle, Assoziationen einer Person werden unmittelbar, oft sprunghaft aus ihrer Perspektive wiedergegeben. Eine Aneinanderreihung diverser Eindrücke ohne klare Syntax. Erzeugt große emotionale Wirkung.",ex:"Die Verabredung heute soll ich müde zuerst ein Stündchen schlafen die Entscheidung kann später fallen halt ich hab ja schon zugesagt ach was."},
{id:"fc-aeussereHandlung",term:"Äußere Handlung",def:"Die Vorgänge, die von außen wahrnehmbar sind. Sie sind auch anderen Figuren des epischen Textes zugänglich. Für das Vorantreiben der äußeren Handlung werden v.a. Erzählerbericht, direkte und indirekte Rede verwendet."},
{id:"fc-innereHandlung",term:"Innere Handlung",def:"Sie umfasst, was in den Personen vorgeht — also wie sie denken, fühlen usw. Erlebte Rede, innerer Monolog und Bewusstseinsstrom geben diese inneren Vorgänge wieder."},
{id:"fc-fabel",term:"Fabel",def:"Eine kurze lehrhafte Dichtung. Handlungsträger sind vorwiegend Tiere, aber auch Pflanzen und Dinge, die mit typischen menschlichen Eigenschaften ausgestattet sind und zumeist charakteristische Stereotype darstellen. Typischer Aufbau: dreigliedrig (Ausgangssituation – Konflikt/Aktion und Reaktion – Lösung). Die Lehre (Moral) kann zu Beginn (Promythion) oder am Ende (Epimythion) stehen. Zeit und Ort werden nicht ausgeführt."},
{id:"fc-parabel",term:"Parabel",def:"Gehört zur Lehrdichtung und trägt einen erzieherischen Gedanken. Die Moral ist üblicherweise NICHT ausgeführt und muss von der Leserin/dem Leser erschlossen werden. Unterschieden werden Bildebene (Geschehen/Handlung) und Sach-/Deutungsebene (Aussage). Findet sich auch als Binnenerzählung, eingebettet in andere epische oder dramatische Werke."},
{id:"fc-anekdote",term:"Anekdote",def:"Eine kurze, auf das Wesentliche beschränkte epische Kleinform. Die zumeist witzige Pointe hat es in sich. Dargestellt wird eine Episode aus dem Leben einer bekannten (historischen) Persönlichkeit, wobei an einem scheinbar zufälligen Detail eine charakteristische Eigenart verdeutlicht wird. Erscheint als historisch verbürgt (genaue Orts- und Zeitangaben), muss aber keineswegs \u201ewahr\u201c sein."},
{id:"fc-kalendergeschichte",term:"Kalendergeschichte",def:"Trägt ihren Namen, weil sie ursprünglich auf der Rückseite von (Volks-)Kalendern abgedruckt war. Kurz, meist volksnah, in an die mündliche Überlieferung angelehnter Sprache. Soll belehren, aber auch unterhalten. Später — vor allem durch Johann Peter Hebel — wurde daraus eine eigenständige literarische Form. Konzentriert sich aufs Wesentliche, beruht häufig auf realen Gegebenheiten (z. B. Kriegen)."},
{id:"fc-kurzgeschichte",term:"Kurzgeschichte",def:"Ursprung in den angloamerikanischen \u201eShort Storys\u201c, die für Zeitschriften und Zeitungen geschrieben wurden. Im deutschsprachigen Raum Blüte nach dem Zweiten Weltkrieg. Zeigt einen kurzen Ausschnitt, einen entscheidenden Einschnitt im Leben einer gewöhnlichen, alltäglichen Person. Formal gekennzeichnet durch relative Kürze, unmittelbaren Einstieg (keine Exposition) und offenen Schluss (oder Pointe). Zumeist ein Handlungsstrang, geringes Personal. Sprache: kurz, prägnant, leicht verständlich."},
{id:"fc-novelle",term:"Novelle",def:"Erzählt etwas Neues, Außergewöhnliches (Goethe: \u201esich ereignete unerhörte Begebenheit\u201c), zumeist einen schicksalsträchtigen Abschnitt im Leben eines Menschen. Die Darstellung des Ungewöhnlichen soll glaubwürdig wirken. Ein Handlungsstrang; Aufbau ähnlich klassischem Drama: Exposition – Steigerung – Peripetie (Wendepunkt) – Abfall – Lösung/Katastrophe. Typisch: ein Dingsymbol (leibloser Gegenstand, Tier oder Pflanze, das als Leitmotiv fungiert). Oft mit Erzählrahmen oder in Novellenzyklen."},
{id:"fc-erzaehlung",term:"Erzählung",def:"Kürzerer epischer Text, nicht nach exakt festgelegten Kriterien bestimmt. Wird häufig über die Unterschiede zu anderen Textsorten definiert: kürzer als ein Roman, einsträngige Handlung, weniger Personal. Weniger streng in der Form als eine Novelle und nicht auf ein oder zwei Hauptereignisse fokussiert. Im Vergleich zur Kurzgeschichte weniger pointiert und nicht so sehr auf den Schluss hin komponiert."},
{id:"fc-roman",term:"Roman",def:"Gehört zu den epischen Großformen. Da er sich über die Jahrhunderte stets verändert hat und keine Formstrenge aufweist, lassen sich kaum Charakteristika verbindlich anführen. Was den Roman von anderen epischen Formen (vor allem der Kleinepik) abgrenzt, sind ein größeres Personal und eine mehrsträngige Handlung, welche am Ende wieder zusammengeführt wird."},
{id:"fc-epos",term:"(Vers-)Epos",def:"Epische Großform. Gleichartig gebaute Verse oder Strophen auf und besteht zumeist aus mehreren Teilen. In gehobener Sprache verfasst. Im Zentrum steht eine bestimmte Person oder ein Leitgedanke. Älteste überlieferte Großform: Gilgamesch-Epos (Babylon), Ilias und Odyssee (Homer, ab 8. Jh. v. Chr.). Im deutschsprachigen Raum v.a. das Nibelungenlied; neueres Beispiel: Goethes \u201eHermann und Dorothea\u201c."}
],
quiz:[
{id:"q1",q:"Welche Erzählperspektive nutzt einen allwissenden Erzähler, der die Gedanken aller Figuren kennt und den Leser direkt ansprechen kann?",opts:["Auktorial","Personal","Neutral","Ich-Erzähler"],correct:0,expl:"Die auktoriale Erzählperspektive (3. Person, Er-/Sie-Form) zeichnet sich durch einen allwissenden Erzähler aus, der die Gedanken der Figuren lesen, kommentieren und den Leser direkt ansprechen kann."},
{id:"q2",q:"Welche Erzählperspektive wird auch \u201eKameraperspektive\u201c genannt?",opts:["Auktorial","Personal","Neutral","Ich-Erzähler"],correct:2,expl:"Die neutrale Erzählperspektive nimmt die Position eines unsichtbaren Beobachters ein — ohne Zugang zu Gedanken oder Gefühlen der Figuren, ohne Kommentare. Man spricht daher von der Kameraperspektive."},
{id:"q3",q:"In welcher Erzählperspektive steht der Text in der 3. Person, aber der Erzähler ist NICHT allwissend?",opts:["Auktorial","Personal","Neutral","Ich-Erzähler"],correct:1,expl:"Die personale Erzählperspektive wird aus Sicht der handelnden Figur(en) dargestellt. Die Erzählfigur ist nicht allwissend."},
{id:"q4",q:"Wie heißt der Handlungszeitraum eines Textes (Tage, Monate, Jahre)?",opts:["Erzählzeit","Erzählte Zeit","Lesezeit","Zeitdeckung"],correct:1,expl:"Die erzählte Zeit bezeichnet den Handlungszeitraum — also die Zeit, die im Text dargestellt wird."},
{id:"q5",q:"Was versteht man unter \u201eErzählzeit\u201c?",opts:["Den Handlungszeitraum","Die Epoche der Entstehung","Die Lesezeit","Das Jahr der Veröffentlichung"],correct:2,expl:"Die Erzählzeit ist die Lesezeit — jene Zeit, die der Leser zum Lesen der Geschichte benötigt."},
{id:"q6",q:"Wenn die Erzählzeit kleiner ist als die erzählte Zeit, spricht man von...",opts:["zeitdehnend","zeitraffend","zeitdeckend","zeitlos"],correct:1,expl:"zeitraffend: Erzählzeit kleiner als erzählte Zeit (z. B. 10 Jahre in 2 Seiten)."},
{id:"q7",q:"Wenn die Erzählzeit größer ist als die erzählte Zeit, spricht man von...",opts:["zeitdehnend","zeitraffend","zeitdeckend","zeitlos"],correct:0,expl:"zeitdehnend: Erzählzeit größer als erzählte Zeit (z. B. 5 Minuten Handlung auf 20 Seiten)."},
{id:"q8",q:"In welcher Personenrede wird typischerweise der Konjunktiv verwendet?",opts:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog"],correct:1,expl:"In der indirekten Rede werden Äußerungen durch den Erzähler wiedergegeben — typischerweise im Konjunktiv. Das schafft Distanz."},
{id:"q9",q:"Was kennzeichnet den Bewusstseinsstrom (Stream of Consciousness)?",opts:["Klare Satzstruktur und logischer Aufbau","Sprunghafte, unmittelbare Gedanken ohne klare Syntax","Dialog zwischen zwei Figuren","Wörtliche Rede mit Anführungszeichen"],correct:1,expl:"Der Bewusstseinsstrom gibt Gedanken und Gefühle unmittelbar und oft sprunghaft wieder — ohne klare Syntax, mit großer emotionaler Wirkung."},
{id:"q10",q:"In welcher Personenrede werden Gedanken aus Sicht der Figur, aber formal in der 3. Person wiedergegeben?",opts:["Direkte Rede","Indirekte Rede","Erlebte Rede","Bewusstseinsstrom"],correct:2,expl:"Die erlebte Rede gibt Gedanken aus Sicht der betroffenen Person wieder, aber in der 3. Person — also formal von einem Erzähler."},
{id:"q11",q:"In welcher Personenrede steht der Text IMMER in der 1. Person und ist reflektierend?",opts:["Direkte Rede","Innerer Monolog","Erlebte Rede","Bewusstseinsstrom"],correct:1,expl:"Der innere Monolog — das \u201eSelbstgespräch\u201c — steht immer in der 1. Person. Im Unterschied zum Bewusstseinsstrom ist er reflektierender."},
{id:"q12",q:"Welche epische Form hat typischerweise einen dreigliedrigen Aufbau mit Promythion oder Epimythion?",opts:["Anekdote","Fabel","Kurzgeschichte","Novelle"],correct:1,expl:"Die Fabel ist dreigliedrig aufgebaut (Ausgangssituation – Konflikt – Lösung). Die Lehre (Moral) kann zu Beginn (Promythion) oder am Ende (Epimythion) stehen."},
{id:"q13",q:"Bei welcher Lehrdichtung wird die Moral üblicherweise NICHT ausgeführt, sondern muss vom Leser erschlossen werden?",opts:["Fabel","Parabel","Kalendergeschichte","Anekdote"],correct:1,expl:"Bei der Parabel ist die Moral üblicherweise nicht ausgeführt. Bildebene und Sach-/Deutungsebene müssen vom Leser verbunden werden."},
{id:"q14",q:"Welche epische Kleinform erzählt eine Episode aus dem Leben einer bekannten (historischen) Persönlichkeit mit einer Pointe?",opts:["Fabel","Kalendergeschichte","Anekdote","Kurzgeschichte"],correct:2,expl:"Die Anekdote ist eine kurze epische Kleinform mit Pointe, die eine Episode aus dem Leben einer bekannten Persönlichkeit darstellt und eine charakteristische Eigenart verdeutlicht."},
{id:"q15",q:"Wer gilt als Hauptvertreter der deutschsprachigen Kalendergeschichte?",opts:["Gotthold Ephraim Lessing","Johann Peter Hebel","Arthur Schopenhauer","Theodor Fontane"],correct:1,expl:"Johann Peter Hebel hat die Kalendergeschichte zu einer eigenständigen literarischen Form mit hohem literarischen Niveau entwickelt."},
{id:"q16",q:"Welche epische Form hat ihren Ursprung in den angloamerikanischen \u201eShort Storys\u201c?",opts:["Novelle","Erzählung","Kurzgeschichte","Anekdote"],correct:2,expl:"Die Kurzgeschichte geht auf die angloamerikanischen \u201eShort Storys\u201c zurück. Im deutschsprachigen Raum erlebte sie ihre Blüte nach dem Zweiten Weltkrieg."},
{id:"q17",q:"Goethe beschrieb diese Form als \u201esich ereignete unerhörte Begebenheit\u201c. Welche ist gemeint?",opts:["Novelle","Roman","Anekdote","Fabel"],correct:0,expl:"Die Novelle erzählt etwas Neues, Außergewöhnliches — Goethe sprach von einer \u201esich ereigneten unerhörten Begebenheit\u201c."},
{id:"q18",q:"Welcher dramenähnliche Aufbau ist typisch für die Novelle?",opts:["Anfang – Mitte – Ende","Exposition – Steigerung – Peripetie – Abfall – Lösung","Ausgangssituation – Konflikt – Lösung","Einleitung – Hauptteil – Schluss"],correct:1,expl:"Die Novelle ist ähnlich wie ein klassisches Drama aufgebaut: Exposition – Steigerung – Peripetie (Wendepunkt) – Abfall – Lösung/Katastrophe."},
{id:"q19",q:"Was ist ein \u201eDingsymbol\u201c — typisch für welche epische Form?",opts:["Ein Reimschema im Epos","Ein lebloser Gegenstand, Tier oder Pflanze als Leitmotiv in einer Novelle","Eine Figur in der Anekdote","Die Pointe einer Kurzgeschichte"],correct:1,expl:"Das Dingsymbol — ein lebloser Gegenstand, Tier oder Pflanze — fungiert in einer Novelle als Leitmotiv, in dem sich der zentrale Konflikt spiegelt."},
{id:"q20",q:"Welche epische Großform ist durch mehrsträngige Handlung und größeres Personal gekennzeichnet?",opts:["Novelle","Roman","Erzählung","Epos"],correct:1,expl:"Der Roman grenzt sich von anderen epischen Formen durch größeres Personal und mehrsträngige Handlung ab, die am Ende wieder zusammengeführt wird."},
{id:"q21",q:"Ilias, Odyssee und das Nibelungenlied sind Beispiele für welche epische Form?",opts:["Roman","Novelle","Epos","Kurzgeschichte"],correct:2,expl:"Das (Vers-)Epos ist die älteste überlieferte epische Großform — mit gleichartig gebauten Versen/Strophen in gehobener Sprache. Ilias, Odyssee und Nibelungenlied sind klassische Beispiele."},
{id:"q22",q:"Mit welchen Mitteln wird die ÄUSSERE Handlung v.a. vorangetrieben?",opts:["Erlebte Rede, innerer Monolog, Bewusstseinsstrom","Erzählerbericht, direkte und indirekte Rede","Nur direkte Rede","Nur innerer Monolog"],correct:1,expl:"Für das Vorantreiben der äußeren Handlung (von außen wahrnehmbar) werden v.a. Erzählerbericht, direkte und indirekte Rede verwendet."},
{id:"q23",q:"Mit welchen Mitteln wird die INNERE Handlung v.a. wiedergegeben?",opts:["Erzählerbericht und direkte Rede","Erlebte Rede, innerer Monolog, Bewusstseinsstrom","Indirekte Rede","Dingsymbole"],correct:1,expl:"Erlebte Rede, innerer Monolog und Bewusstseinsstrom geben die inneren Vorgänge (Denken, Fühlen) wieder."},
{id:"q24",q:"Was versteht man unter einem \u201eErzählerbericht\u201c?",opts:["Gedanken einer Figur in der 1. Person","Alle Aussagen, die vom Erzähler (nicht von einer Figur) getätigt werden","Eine Nacherzählung durch den Leser","Die Exposition eines Romans"],correct:1,expl:"Unter Erzählerbericht versteht man alle Aussagen, die nicht von einer Figur, sondern vom Erzähler getätigt werden."}
],
texts:[
{id:"t-sandmann",author:"E. T. A. Hoffmann",work:"Der Sandmann",year:1816,kind:"perspektive",
choices:["Auktorial","Personal","Neutral","Ich-Erzähler"],correct:3,
text:"Das Wunderbare, Seltsame davon erfüllte meine ganze Seele, aber dann deshalb und weil ich, Dich, o mein Leser! gleich geneigt machen müsste, Wunderliches zu ertragen, welches nichts Geringes ist, quälte ich mich ab, Nathaniels Geschichte, bedeutend – originell, ergreifend, zu beginnen: \u201eEs war einmal!\u201c – der schönste Anfang jeder Erzählung, zu nüchtern! [...]",
expl:"Der Erzähler spricht in der 1. Person Singular (\u201emeine ganze Seele\u201c, \u201equälte ich mich ab\u201c) und wendet sich direkt an den Leser (\u201eDich, o mein Leser\u201c). Das ist der Ich-Erzähler."},
{id:"t-faenger",author:"J. D. Salinger",work:"Der Fänger im Roggen",year:1951,kind:"perspektive",
choices:["Auktorial","Personal","Neutral","Ich-Erzähler"],correct:3,
text:"Alle schlüpften oder wann sonst übers Wochenende zu Hause, und auf dem Gang war es sehr, sehr still und deprimierend. Vor Leahys und Hoffmans Tür lag eine riesige Schachtel von Kolynos-Zahnpasta, auf dem Weg zur Treppe kickte ich sie mit dem Schaffellpantoffel, den ich trug, vor mir her. Ich dachte, also ich dachte, ich wollte mal noch einen sehen und sehen, was der gute Mal Brossard so trieb. Aber auf einmal überlegte ich es mir anders. Auf einmal beschloss ich, was ich wirklich wollte, nämlich vor der Pencey abhauen — noch in dieser Nacht und so. Also, nicht bis Mittwoch warten oder was. Ich wollte hier einfach nicht mehr bleiben.",
expl:"Der Text ist durchgehend in der 1. Person erzählt (\u201eich trug\u201c, \u201eich dachte\u201c, \u201eich beschloss\u201c). Die Ich-Figur berichtet aus ihrer subjektiven Sicht."},
{id:"t-ulysses",author:"James Joyce",work:"Ulysses",year:1922,kind:"personenrede",
choices:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog","Bewusstseinsstrom"],correct:4,
text:"Zuerst will ich mal etwas saubermachen in der Wohnung ich glaube der Staub wächst sogar während ich am Schlafen bin dann können wir etwas musizieren und Zigaretten rauchen ich kann ihn begleiten aber zuerst muß ich noch die Tasten vom Klavier säubern mit Milch was zieh ich denn an soll ich eine weiße Rose tragen oder haltmal diese schönen Kuchen bei Lipton also ich liebe ja diesen Duft in einem reichen großen Laden zu 7 1/2 d das Pfund oder die anderen mit den Kirschen drin und der rosa Zucker 11 d das Kilo und natürlich eine schöne Topfpflanze für mitten auf den Tisch die krieg ich doch billiger bei Moment wo war das doch ich hab die doch kürzlich erst gesehen [...]",
expl:"Gedanken werden unmittelbar, sprunghaft und ohne klare Syntax aneinandergereiht — keine Satzzeichen, keine geordnete Reflexion. Das ist der Bewusstseinsstrom (Stream of Consciousness)."},
{id:"t-effi",author:"Theodor Fontane",work:"Effi Briest",year:1895,kind:"personenrede",
choices:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog","Bewusstseinsstrom"],correct:0,
text:"\u201eGewiss ist es der Richtige. Das verstehst du nicht, Hertha. Jeder ist der Richtige. Natürlich muss er von Adel sein und eine Stellung haben und gut aussehen.\u201c \u201eGott, Effi, wie du nur sprichst. Sonst sprichst du doch ganz anders.\u201c \u201eJa, sonst.\u201c \u201eUnd bist du auch schon ganz glücklich?\u201c \u201eWenn man zwei Stunden verlobt ist, ist man immer ganz glücklich. Wenigstens denke ich es mir so.\u201c",
expl:"Die Äußerungen der Figuren werden wörtlich wiedergegeben und mit Anführungszeichen markiert. Das ist direkte Rede."},
{id:"t-vermessung",author:"Daniel Kehlmann",work:"Die Vermessung der Welt",year:2005,kind:"personenrede",
choices:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog","Bewusstseinsstrom"],correct:1,
text:"Während des sparsam zubereiteten Festmahls sprach Gauß' Vater darüber, dass man sich nicht beugen lassen dürfe, niemals, von keinem, dann erhob sich Zimmermann, öffnete den Mund, lächelte liebenswürdig in die Runde und setzte sich wieder. Bartels stieß Gauß an. Der stand auf, schluckte und sagte, er habe nicht erwartet, dass er etwas wie Glück finden würde, und im Grunde genommen glaube er auch jetzt nicht daran. Es komme ihm wie ein Rechenfehler vor, ein Irrtum, von dem er hoffe, keiner werde ihn aufdecken. Er nahm wieder Platz und wunderte sich über die fassungslosen Blicke. Leise fragte er Johanna, ob er etwas Falsches gesagt habe. Aber woher denn, antwortete sie. Genau diese Rede habe sie sich immer für ihre Hochzeit erträumt.",
expl:"Die Äußerungen werden durchgehend im Konjunktiv durch den Erzähler wiedergegeben (\u201edürfe\u201c, \u201ehabe\u201c, \u201eglaube\u201c, \u201ekomme\u201c, \u201ehoffe\u201c, \u201ewerde aufdecken\u201c). Das ist indirekte Rede."},
{id:"t-gustl",author:"Arthur Schnitzler",work:"Lieutenant Gustl",year:1900,kind:"personenrede",
choices:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog","Bewusstseinsstrom"],correct:3,
text:"Wie lang wird denn das noch dauern? Ich muß auf die Uhr schauen ... schickt sich wahrscheinlich nicht in einem so ernsten Konzert. Aber wer sieht's denn? Wenn's einer sieht, so paßt er gerade so wenig auf wie ich, und vor dem brauch' ich mich nicht zu genieren ... Erst viertel auf zehn? ... Mir kommt vor, ich sitz' schon drei Stunden in dem Konzert. Ich bin's halt nicht gewohnt ... Was ist es denn eigentlich? Ich muß das Programm anschauen ... Ja, richtig: Oratorium! Ich hab' gemeint: Messe. Solche Sachen gehören doch nur in die Kirche! Die Kirche hat auch das Gute, daß man jeden Augenblick fortgehen kann. –",
expl:"Der Text steht in der 1. Person und ist ein reflektierendes \u201eSelbstgespräch\u201c Gustls — ohne Erzähler, mit klarer Syntax aber spontanen Gedanken. Das ist der innere Monolog (\u201eLieutenant Gustl\u201c gilt als kanonisches Beispiel in der deutschsprachigen Literatur)."},
{id:"t-tonio",author:"Thomas Mann",work:"Tonio Kröger",year:1903,kind:"personenrede",
choices:["Direkte Rede","Indirekte Rede","Erlebte Rede","Innerer Monolog","Bewusstseinsstrom"],correct:2,
text:"Er blickte in sich hinein, wo so viel Gram und Sehnsucht war. Warum, warum war er hier? Warum saß er nicht in seiner Stube am Fenster und las in Storms \u201eImmensee\u201c und blickte hie und da in den abendlichen Garten hinaus, wo der alte Walnussbaum schwerfällig knarrte? Das wäre sein Platz gewesen. Mochten die anderen tanzen und frisch und geschickt bei der Sache sein!",
expl:"Die Gedanken stammen klar aus Tonios Perspektive (\u201eWarum war er hier?\u201c — seine Fragen), werden aber formal in der 3. Person wiedergegeben (\u201eer\u201c). Das ist erlebte Rede."}
]
});
