/*
  Latin -> German vocabulary set — "Latein 1" (ids 1-340, stable).
  Fields:
    a      Latin lemma (used for the quiz)
    b      German meaning (used for the quiz)
    u      chapter number (1-15)
    forms  optional: Spezialformen (display only, not matched by quiz)
    loan   optional: Fremdwörter / Lehnwörter (display only)
*/
(window.VOCAB_REGISTRY=window.VOCAB_REGISTRY||[]).push({
  id:"la-de",
  name:"Latein 1. Klasse",
  langA:"Latein",
  langB:"Deutsch",
  flagA:"🏛️",
  flagB:"🇩🇪",
  stripArticlesOnB:true,
  stripArticlesOnA:false,
  vocab:[
{id:1,a:"a, ab",b:"weg von",u:"6",forms:"+ Ablativ"},
{id:2,a:"accusare",b:"anklagen",u:"14",forms:"accuso, accusavi, accusatum",loan:"der Akkusativ"},
{id:3,a:"criminis accusare",b:"für ein Verbrechen anklagen",u:"14",forms:"+ Gen."},
{id:4,a:"ad",b:"zu, an, bei",u:"5",forms:"+ Akkusativ"},
{id:5,a:"adiuvare",b:"unterstützen, helfen",u:"5",forms:"adiuvo, adiuvi, adiutum",loan:"der Adjutant / die Adjutantin"},
{id:6,a:"agere",b:"tun, machen, handeln",u:"9",forms:"ago, egi, actum",loan:"agieren"},
{id:7,a:"gratias agere",b:"danken",u:"9"},
{id:8,a:"alius",b:"ein anderer",u:"12",forms:"alia f., aliud n."},
{id:9,a:"alius ... alius",b:"einer ... ein anderer",u:"12"},
{id:10,a:"alter",b:"der andere",u:"14",forms:"altera f., alterum n. (Gen. alterius, Dat. alteri)",loan:"die Alternative"},
{id:11,a:"alter ... alter",b:"der eine ... der andere",u:"14"},
{id:12,a:"amare",b:"lieben",u:"5",forms:"amo, amavi, amatum",loan:"der Amateur / die Amateurin"},
{id:13,a:"ambulare",b:"spazieren",u:"12",forms:"ambulo, ambulavi, ambulatum",loan:"ambulant, engl. ambulance"},
{id:14,a:"amicus / amica",b:"der Freund / die Freundin",u:"5",forms:"amici / amicae",loan:"amikal"},
{id:15,a:"amor",b:"die Liebe, der Liebesgott",u:"10",forms:"amoris",loan:"Amor"},
{id:16,a:"animal",b:"das Tier, das Lebewesen",u:"15",forms:"animalis",loan:"animalisch, engl. animal"},
{id:17,a:"animus",b:"der Sinn, der Mut, das Herz",u:"6",forms:"animi",loan:"animieren"},
{id:18,a:"in animo habere",b:"im Sinn haben, beabsichtigen",u:"7"},
{id:19,a:"ante",b:"vor",u:"5",forms:"+ Akkusativ"},
{id:20,a:"appellare",b:"nennen",u:"5",forms:"appello, appellavi, appellatum",loan:"appellieren"},
{id:21,a:"apud",b:"bei",u:"5",forms:"+ Akkusativ"},
{id:22,a:"aqua",b:"das Wasser",u:"2",forms:"aquae",loan:"das Aquarium"},
{id:23,a:"arma",b:"die Waffen, die Geräte",u:"12",forms:"armorum (n. Pl.)",loan:"die Armatur, die Armee"},
{id:24,a:"ars",b:"die Kunst",u:"15",forms:"artis",loan:"der Artist / die Artistin"},
{id:25,a:"at",b:"aber",u:"11"},
{id:26,a:"audire",b:"hören",u:"4",forms:"audio, audivi, auditum",loan:"audiovisuell"},
{id:27,a:"aurum",b:"das Gold",u:"2",forms:"auri",loan:"Au (chem. Zeichen)"},
{id:28,a:"autem",b:"aber",u:"8"},
{id:29,a:"auxilium",b:"die Hilfe, die Unterstützung",u:"4",forms:"auxilii"},
{id:30,a:"bene",b:"gut",u:"7",forms:"(von bonus)",loan:"die Benefizveranstaltung"},
{id:31,a:"bestia",b:"wildes Tier",u:"15",forms:"bestiae",loan:"die Bestie"},
{id:32,a:"bonus",b:"gut",u:"6",forms:"bona f., bonum n.",loan:"der Bonus, der Bon, das Bonbon"},
{id:33,a:"caelum",b:"der Himmel",u:"8",forms:"caeli"},
{id:34,a:"canis",b:"der Hund",u:"15",forms:"canis"},
{id:35,a:"capere",b:"fangen, nehmen, ergreifen, packen",u:"2",forms:"capio, cepi, captum",loan:"kapieren"},
{id:36,a:"caput",b:"der Kopf",u:"9",forms:"capitis",loan:"das Kapitel, die Kapuze"},
{id:37,a:"casus",b:"der Fall, der Zufall",u:"9",forms:"casus",loan:"engl. casual"},
{id:38,a:"causa",b:"der Grund",u:"2",forms:"causae",loan:"kausal"},
{id:39,a:"celeber",b:"berühmt, gefeiert",u:"13",forms:"celebris f., celebre n. (Gen. celebris)",loan:"zelebrieren"},
{id:40,a:"cena",b:"das Essen, die Mahlzeit",u:"4",forms:"cenae"},
{id:41,a:"cenare",b:"essen, speisen",u:"4",forms:"ceno, cenavi, cenatum"},
{id:42,a:"centum",b:"hundert",u:"13",loan:"der Zentimeter, der Cent"},
{id:43,a:"cibus",b:"die Speise",u:"3",forms:"cibi"},
{id:44,a:"circum",b:"um ... herum",u:"5",forms:"+ Akkusativ"},
{id:45,a:"civis",b:"der Bürger",u:"9",forms:"civis",loan:"zivil"},
{id:46,a:"clamare",b:"schreien, rufen",u:"5",forms:"clamo, clamavi, clamatum",loan:"die Reklame"},
{id:47,a:"clarus",b:"hell, klar, berühmt",u:"9",forms:"clara f., clarum n.",loan:"klar"},
{id:48,a:"cogitare",b:"denken",u:"7",forms:"cogito, cogitavi, cogitatum"},
{id:49,a:"cognoscere",b:"erkennen, kennenlernen",u:"12",forms:"cognosco, cognovi, cognitum",loan:"kognitiv"},
{id:50,a:"colere",b:"pflegen, bebauen, verehren",u:"8",forms:"colo, colui, cultum",loan:"die Kultur, der Kult"},
{id:51,a:"color",b:"die Farbe",u:"15",forms:"coloris",loan:"kolorieren"},
{id:52,a:"consilium",b:"der Rat, der Plan",u:"10",forms:"consilii"},
{id:53,a:"consilium capere",b:"einen Plan fassen",u:"10"},
{id:54,a:"constans",b:"gleichmäßig, standhaft",u:"13",forms:"constans f., constans n. (Gen. constantis)",loan:"die Konstante"},
{id:55,a:"constituere",b:"festsetzen, beschließen",u:"14",forms:"constituo, constitui, constitutum",loan:"die Konstitution"},
{id:56,a:"contra",b:"gegen",u:"9",forms:"+ Akkusativ",loan:"pro und contra"},
{id:57,a:"corpus",b:"der Körper",u:"12",forms:"corporis",loan:"der Korporal"},
{id:58,a:"cottidie",b:"täglich",u:"2"},
{id:59,a:"crimen",b:"das Verbrechen, der Vorwurf",u:"14",forms:"criminis",loan:"der Krimi"},
{id:60,a:"crux",b:"das Kreuz",u:"10",forms:"crucis",loan:"das Kruzifix"},
{id:61,a:"cum (+ Indikativ)",b:"wenn, als",u:"3",forms:"+ Indikativ"},
{id:62,a:"cum (+ Ablativ)",b:"mit",u:"6",forms:"+ Ablativ"},
{id:63,a:"cuncti",b:"alle",u:"4",forms:"cunctae f., cuncta n."},
{id:64,a:"cupere",b:"wünschen, wollen",u:"4",forms:"cupio, cupivi, cupitum"},
{id:65,a:"cupidus",b:"gierig",u:"7",forms:"cupida f., cupidum n.",loan:"Cupido"},
{id:66,a:"cur?",b:"warum?",u:"2"},
{id:67,a:"currere",b:"laufen",u:"15",forms:"curro, cucurri, cursum"},
{id:68,a:"cursus",b:"die Bahn",u:"15",forms:"cursus",loan:"der Kurs"},
{id:69,a:"currus",b:"der Wagen",u:"15",forms:"currus"},
{id:70,a:"custodire",b:"bewachen",u:"10",forms:"custodio, custodivi, custoditum",loan:"der Kustos / die Kustodin"},
{id:71,a:"dare",b:"geben, schenken",u:"4",forms:"do, dedi, datum",loan:"das Datum"},
{id:72,a:"de",b:"von, über",u:"6",forms:"+ Ablativ"},
{id:73,a:"debere",b:"müssen, sollen, schulden, verdanken",u:"3",forms:"debeo, debui, debitum"},
{id:74,a:"delectare",b:"erfreuen, unterhalten",u:"9",forms:"delecto, delectavi, delectatum",loan:"delektieren"},
{id:75,a:"deus / dea",b:"der Gott / die Göttin",u:"5",forms:"dei (di) / deae",loan:"Adieu"},
{id:76,a:"dicere",b:"sagen, sprechen, nennen",u:"4",forms:"dico, dixi, dictum",loan:"diktieren"},
{id:77,a:"dies",b:"der Tag",u:"9",forms:"diei",loan:"engl. diary"},
{id:78,a:"differre",b:"aufschieben",u:"13",forms:"differo, distuli, dilatum",loan:"die Differenz"},
{id:79,a:"docere",b:"lehren",u:"1",forms:"doceo, docui, doctum",loan:"der Dozent / die Dozentin"},
{id:80,a:"doctus",b:"gelehrt, gebildet",u:"7",forms:"docta f., doctum n.",loan:"der Doktor / die Doktorin"},
{id:81,a:"dolere",b:"trauern, Schmerz fühlen, leiden",u:"10",forms:"doleo, dolui",loan:"kondolieren"},
{id:82,a:"dominus",b:"der Herr",u:"15",forms:"domini",loan:"dominieren"},
{id:83,a:"donum",b:"das Geschenk",u:"4",forms:"doni"},
{id:84,a:"dormire",b:"schlafen",u:"13",forms:"dormio, dormivi, dormitum",loan:"engl. dormitory"},
{id:85,a:"ducere",b:"führen",u:"11",forms:"duco, duxi, ductum",loan:"das Produkt, induzieren"},
{id:86,a:"dulcis",b:"angenehm, süß",u:"13",forms:"dulcis f., dulce n. (Gen. dulcis)"},
{id:87,a:"durus",b:"hart",u:"11",forms:"dura f., durum n.",loan:"die Dur-Tonleiter"},
{id:88,a:"e, ex",b:"aus, heraus",u:"6",forms:"+ Ablativ"},
{id:89,a:"ego",b:"ich",u:"3",loan:"der Egoist / die Egoistin"},
{id:90,a:"enim",b:"nämlich, denn",u:"5"},
{id:91,a:"equus",b:"das Pferd",u:"15",forms:"equi"},
{id:92,a:"esse",b:"sein",u:"1",forms:"sum, fui",loan:"die Essenz"},
{id:93,a:"et",b:"und",u:"1"},
{id:94,a:"et ... et",b:"sowohl ... als auch",u:"12"},
{id:95,a:"etiam",b:"auch, sogar",u:"7"},
{id:96,a:"exemplum",b:"das Beispiel",u:"3",forms:"exempli",loan:"das Exempel"},
{id:97,a:"exercere",b:"üben, trainieren",u:"12",forms:"exerceo, exercui, exercitum",loan:"exerzieren, engl. exercise"},
{id:98,a:"exspectare",b:"erwarten",u:"12",forms:"exspecto, exspectavi, exspectatum",loan:"engl. expect"},
{id:99,a:"fabula",b:"die Fabel, die Geschichte",u:"1",forms:"fabulae",loan:"fabelhaft"},
{id:100,a:"facere",b:"machen, tun",u:"3",forms:"facio, feci, factum",loan:"faktisch"},
{id:101,a:"factum",b:"die Tat, die Handlung",u:"3",forms:"facti",loan:"der Fakt, das Faktum"},
{id:102,a:"femina",b:"die Frau",u:"2",forms:"feminae",loan:"feminin"},
{id:103,a:"ferox",b:"wild, grausam",u:"15",forms:"ferox f., ferox n. (Gen. ferocis)"},
{id:104,a:"ferre",b:"tragen, bringen, ertragen",u:"7",forms:"fero, tuli, latum",loan:"das Referat"},
{id:105,a:"fides",b:"die Treue",u:"9",forms:"fidei",loan:"engl. high fidelity"},
{id:106,a:"figere",b:"befestigen",u:"10",forms:"figo, fixi, fixum",loan:"fix, fixieren"},
{id:107,a:"filia",b:"die Tochter",u:"3",forms:"filiae",loan:"die Filiale"},
{id:108,a:"filius",b:"der Sohn",u:"3",forms:"filii"},
{id:109,a:"finis",b:"das Ende, die Grenze; Pl. das Gebiet",u:"14",forms:"finis",loan:"das Finale"},
{id:110,a:"fluvius",b:"der Fluss",u:"7",forms:"fluvii",loan:"das Fluor"},
{id:111,a:"fortis",b:"stark, tapfer",u:"13",forms:"fortis f., forte n. (Gen. fortis)",loan:"forte"},
{id:112,a:"gaudere",b:"sich freuen",u:"4",forms:"gaudeo, gavisus sum",loan:"die Gaudi"},
{id:113,a:"gaudium",b:"die Freude",u:"6",forms:"gaudii",loan:"die Gaudi"},
{id:114,a:"gladiator",b:"der Gladiator, der Schwertkämpfer",u:"15",forms:"gladiatoris"},
{id:115,a:"gladius",b:"das Schwert",u:"14",forms:"gladii",loan:"der Gladiator, die Gladiole"},
{id:116,a:"gratia",b:"der Dank, die Anmut",u:"6",forms:"gratiae",loan:"engl. grace"},
{id:117,a:"gratiam agere",b:"danken",u:"6"},
{id:118,a:"gravis",b:"schwer, gewichtig, wichtig",u:"15",forms:"gravis f., grave n. (Gen. gravis)",loan:"die Gravitation"},
{id:119,a:"habere",b:"haben",u:"2",forms:"habeo, habui, habitum"},
{id:120,a:"habitare",b:"wohnen",u:"13",forms:"habito, habitavi, habitatum",loan:"das Habitat"},
{id:121,a:"hic",b:"dieser, diese, dieses",u:"10",forms:"haec f., hoc n. (Gen. huius)"},
{id:122,a:"hodie",b:"heute",u:"8",forms:"(<hoc + die)"},
{id:123,a:"homo",b:"der Mensch, der Mann",u:"9",forms:"hominis",loan:"homo sapiens"},
{id:124,a:"honor",b:"die Ehre",u:"11",forms:"honoris",loan:"honorieren"},
{id:125,a:"hora",b:"die Stunde",u:"10",forms:"horae",loan:"engl. hour"},
{id:126,a:"horrere",b:"fürchten, nicht leiden können",u:"11",forms:"horreo, horrui",loan:"der Horror"},
{id:127,a:"hospes",b:"der Gast, der Gastfreund",u:"14",forms:"hospitis",loan:"das Hospital, das Hospiz"},
{id:128,a:"huius modi / eius modi",b:"von dieser Art, derartig",u:"10"},
{id:129,a:"iam",b:"schon",u:"9"},
{id:130,a:"ibi",b:"dort",u:"15",loan:"das Alibi"},
{id:131,a:"idem",b:"derselbe, dieselbe, dasselbe",u:"14",forms:"eadem f., idem n. (Gen. eiusdem)",loan:"ident"},
{id:132,a:"igitur",b:"also, folglich, daher",u:"8"},
{id:133,a:"ille",b:"jener, jene, jenes",u:"10",forms:"illa f., illud n. (Gen. illius)"},
{id:134,a:"imperator",b:"der Herrscher, der Kaiser, der Feldherr",u:"11",forms:"imperatoris",loan:"der Imperativ"},
{id:135,a:"imperium",b:"das Reich, die Herrschaft, der Befehl",u:"11",forms:"imperii",loan:"engl. empire"},
{id:136,a:"in (+ Akkusativ)",b:"zu, in (hinein), gegen",u:"5",forms:"+ Akkusativ"},
{id:137,a:"in (+ Ablativ)",b:"in, an, auf, bei",u:"6",forms:"+ Ablativ"},
{id:138,a:"insula",b:"die Insel",u:"5",forms:"insulae",loan:"isoliert"},
{id:139,a:"intellegere",b:"verstehen, bemerken",u:"3",forms:"intellego, intellexi, intellectum",loan:"die Intelligenz"},
{id:140,a:"inter",b:"zwischen, unter",u:"15",forms:"+ Akkusativ",loan:"international"},
{id:141,a:"interrogare",b:"fragen",u:"1",forms:"interrogo, interrogavi, interrogatum",loan:"der Interrogativ"},
{id:142,a:"intrare",b:"eintreten, betreten",u:"6",forms:"intro, intravi, intratum",loan:"engl. enter"},
{id:143,a:"invenire",b:"finden, erfinden",u:"14",forms:"invenio, inveni, inventum",loan:"das Inventar, engl. invention"},
{id:144,a:"invitare",b:"einladen",u:"6",forms:"invito, invitavi, invitatum",loan:"engl. invite"},
{id:145,a:"ipse",b:"selbst, genau, direkt",u:"13",forms:"ipsa f., ipsum n. (Gen. ipsius)",loan:"der Solipsist / die Solipsistin"},
{id:146,a:"ire",b:"gehen",u:"4",forms:"eo, ii, itum"},
{id:147,a:"is",b:"dieser, diese, dieses; der, die, das; er, sie, es",u:"10",forms:"ea f., id n. (Gen. eius)"},
{id:148,a:"itaque",b:"daher",u:"2"},
{id:149,a:"iter",b:"der Weg, die Reise, der Marsch",u:"9",forms:"itineris"},
{id:150,a:"iter facere",b:"reisen",u:"13"},
{id:151,a:"iterum",b:"wieder, wiederum",u:"13"},
{id:152,a:"iubere",b:"befehlen",u:"4",forms:"iubeo, iussi, iussum (+ Akkusativ)"},
{id:153,a:"iudex",b:"der Richter",u:"14",forms:"iudicis",loan:"judizieren"},
{id:154,a:"ius",b:"das Recht",u:"9",forms:"iuris",loan:"der Jurist / die Juristin"},
{id:155,a:"iustus",b:"gerecht",u:"9",forms:"iusta f., iustum n.",loan:"engl. justice"},
{id:156,a:"labor",b:"die Arbeit, die Mühe",u:"9",forms:"laboris",loan:"das Labor"},
{id:157,a:"laborare",b:"arbeiten, sich abmühen",u:"3",forms:"laboro, laboravi, laboratum",loan:"laborieren, das Labor"},
{id:158,a:"laudare",b:"loben",u:"9",forms:"laudo, laudavi, laudatum",loan:"die Laudatio"},
{id:159,a:"lavare",b:"waschen, baden",u:"12",forms:"lavo, lavi, lautum",loan:"engl. lavatory"},
{id:160,a:"legere",b:"lesen",u:"12",forms:"lego, legi, lectum",loan:"die Lektüre"},
{id:161,a:"leo",b:"der Löwe",u:"12",forms:"leonis"},
{id:162,a:"liber",b:"das Buch",u:"13",forms:"libri",loan:"engl. library"},
{id:163,a:"liberare",b:"befreien",u:"4",forms:"libero, liberavi, liberatum",loan:"der Libero / die Libera"},
{id:164,a:"locus",b:"der Ort, der Platz, die Stelle",u:"8",forms:"loci",loan:"das Lokal"},
{id:165,a:"longus",b:"lang",u:"7",forms:"longa f., longum n.",loan:"prolongieren"},
{id:166,a:"lux",b:"das Licht",u:"9",forms:"lucis"},
{id:167,a:"luce clarius",b:"sonnenklar",u:"9"},
{id:168,a:"magister",b:"der Lehrer",u:"3",forms:"magistri",loan:"der Meister / die Meisterin"},
{id:169,a:"magnus",b:"groß",u:"1",forms:"magna f., magnum n.",loan:"die Magnum"},
{id:170,a:"malus",b:"böse, schlecht",u:"2",forms:"mala f., malum n."},
{id:171,a:"mane",b:"morgens",u:"13"},
{id:172,a:"manere",b:"bleiben",u:"10",forms:"maneo, mansi, mansum",loan:"permanent"},
{id:173,a:"manus",b:"die Hand",u:"9",forms:"manus",loan:"manuell"},
{id:174,a:"mater",b:"die Mutter",u:"3",forms:"matris",loan:"das Matriarchat"},
{id:175,a:"maxime",b:"am meisten",u:"7",loan:"maximal, der Maxirock"},
{id:176,a:"maximus",b:"der größte, ein sehr großer",u:"8",forms:"maxima f., maximum n.",loan:"das Maximum"},
{id:177,a:"me",b:"mich",u:"2"},
{id:178,a:"a me",b:"von mir",u:"2"},
{id:179,a:"mecum",b:"mit mir",u:"2"},
{id:180,a:"medius",b:"der mittlere",u:"8",forms:"media f., medium n.",loan:"das Medium"},
{id:181,a:"meridies",b:"der Mittag",u:"9",forms:"meridiei",loan:"der Meridian"},
{id:182,a:"mihi",b:"mir",u:"2"},
{id:183,a:"miles",b:"der Soldat",u:"10",forms:"militis",loan:"das Militär"},
{id:184,a:"mille",b:"tausend",u:"13",loan:"die Million"},
{id:185,a:"minime",b:"keineswegs, am wenigsten, überhaupt nicht",u:"11",loan:"minimal"},
{id:186,a:"minister",b:"der Diener",u:"4",forms:"ministri",loan:"der Minister / die Ministerin, der Ministrant / die Ministrantin"},
{id:187,a:"minus",b:"weniger",u:"11",loan:"das Minus"},
{id:188,a:"miser",b:"arm, elend, unglücklich",u:"5",forms:"misera f., miserum n.",loan:"miserabel"},
{id:189,a:"mittere",b:"schicken, senden",u:"14",forms:"mitto, misi, missum",loan:"die Mission"},
{id:190,a:"modus",b:"die Art, die Weise",u:"10",forms:"modi",loan:"die Mode"},
{id:191,a:"hoc modo",b:"auf diese Weise",u:"10"},
{id:192,a:"monere",b:"warnen, mahnen, kritisieren",u:"7",forms:"moneo, monui, monitum",loan:"monieren"},
{id:193,a:"monstrare",b:"zeigen",u:"8",forms:"monstro, monstravi, monstratum",loan:"die Demonstration"},
{id:194,a:"mors",b:"der Tod",u:"10",forms:"mortis",loan:"der Salto mortale"},
{id:195,a:"mortem obire",b:"sterben",u:"10"},
{id:196,a:"mortuus",b:"tot",u:"10",forms:"mortua f., mortuum n."},
{id:197,a:"mos",b:"die Sitte, der Brauch, die Gewohnheit, der Charakter",u:"13",forms:"moris; Pl. mores, morum",loan:"die Moral"},
{id:198,a:"movere",b:"bewegen",u:"15",forms:"moveo, movi, motum",loan:"der Motor"},
{id:199,a:"mox",b:"bald",u:"1"},
{id:200,a:"mulier",b:"die Frau",u:"10",forms:"mulieris"},
{id:201,a:"multus",b:"viel",u:"2",forms:"multa f., multum n.",loan:"multiplizieren"},
{id:202,a:"mundus",b:"die Welt",u:"8",forms:"mundi",loan:"Minimundus"},
{id:203,a:"mutare",b:"verwandeln, verändern",u:"4",forms:"muto, mutavi, mutatum",loan:"die Mutation"},
{id:204,a:"narrare",b:"erzählen",u:"1",forms:"narro, narravi, narratum"},
{id:205,a:"navigare",b:"segeln, mit dem Schiff fahren",u:"7",forms:"navigo, navigavi, navigatum",loan:"navigieren, das Navi, engl. navy"},
{id:206,a:"-ne / nonne",b:"Fragepartikel (unübersetzt / nicht)",u:"10",forms:"Fragepartikel"},
{id:207,a:"negare",b:"verneinen",u:"1",forms:"nego, negavi, negatum",loan:"negativ"},
{id:208,a:"nihil",b:"nichts",u:"15",loan:"der Nihilist / die Nihilistin"},
{id:209,a:"nobilis",b:"vornehm",u:"13",forms:"nobilis f., nobile n. (Gen. nobilis)",loan:"nobel"},
{id:210,a:"nomen",b:"der Name",u:"13",forms:"nominis",loan:"nominieren"},
{id:211,a:"non",b:"nicht",u:"1",loan:"nonverbal"},
{id:212,a:"nos",b:"wir, uns",u:"14"},
{id:213,a:"notus",b:"bekannt",u:"12",forms:"nota f., notum n.",loan:"notieren, engl. notebook"},
{id:214,a:"novus",b:"neu",u:"2",forms:"nova f., novum n.",loan:"das Novum, die Novität"},
{id:215,a:"nox",b:"die Nacht",u:"14",forms:"noctis",loan:"das Äquinoktium"},
{id:216,a:"nudus",b:"nackt",u:"13",forms:"nuda f., nudum n.",loan:"der Nudist / die Nudistin"},
{id:217,a:"nullus",b:"kein",u:"2",forms:"nulla f., nullum n. (Gen. nullius, Dat. nulli)",loan:"die Null"},
{id:218,a:"num",b:"etwa (Fragepartikel)",u:"10",forms:"Fragepartikel"},
{id:219,a:"nunc",b:"jetzt, nun",u:"4"},
{id:220,a:"nuntiare",b:"melden",u:"8",forms:"nuntio, nuntiavi, nuntiatum",loan:"engl. announce"},
{id:221,a:"occidere",b:"töten",u:"12",forms:"occido, occidi, occisum"},
{id:222,a:"omnis",b:"jeder, alle",u:"13",forms:"omnis f., omne n. (Gen. omnis)",loan:"der Omnibus"},
{id:223,a:"oratio",b:"die Rede",u:"9",forms:"orationis"},
{id:224,a:"orationem habere",b:"eine Rede halten",u:"9"},
{id:225,a:"parare",b:"vorbereiten, zubereiten",u:"4",forms:"paro, paravi, paratum",loan:"parat"},
{id:226,a:"parare (+ Inf.)",b:"sich daran machen",u:"4"},
{id:227,a:"sibi parare",b:"sich verschaffen",u:"4"},
{id:228,a:"parere",b:"gehorchen",u:"5",forms:"pareo, parui",loan:"parieren"},
{id:229,a:"parvus",b:"klein",u:"9",forms:"parva f., parvum n."},
{id:230,a:"pater",b:"der Vater",u:"2",forms:"patris",loan:"der Patriarch"},
{id:231,a:"patria",b:"die Heimat, das Vaterland",u:"7",forms:"patriae",loan:"der Patriot / die Patriotin"},
{id:232,a:"paulo",b:"wenig",u:"5"},
{id:233,a:"paulo post",b:"wenig später",u:"5"},
{id:234,a:"paulo ante",b:"wenig früher",u:"5"},
{id:235,a:"pecunia",b:"das Geld",u:"11",forms:"pecuniae",loan:"pekuniär"},
{id:236,a:"petere",b:"anstreben, zu erreichen suchen, bitten",u:"12",forms:"peto, petivi, petitum (+ a/ab)",loan:"die Petition, der Appetit"},
{id:237,a:"placere",b:"gefallen",u:"8",forms:"placeo, placui, placitum",loan:"das Placebo"},
{id:238,a:"plebs",b:"(einfaches) Volk",u:"12",forms:"plebis",loan:"der Plebejer / die Plebejerin"},
{id:239,a:"plus",b:"mehr",u:"11",loan:"das Plus"},
{id:240,a:"poeta",b:"der Dichter",u:"10",forms:"poetae",loan:"der Poet / die Poetin"},
{id:241,a:"ponere",b:"stellen, setzen, legen",u:"13",forms:"pono, posui, positum",loan:"die Position"},
{id:242,a:"populus",b:"das Volk",u:"8",forms:"populi",loan:"der Pop, populär, engl. people"},
{id:243,a:"portare",b:"tragen, bringen",u:"1",forms:"porto, portavi, portatum",loan:"das Porto"},
{id:244,a:"posse",b:"können",u:"5",forms:"possum, potui",loan:"das Potenzial"},
{id:245,a:"post",b:"nach, hinter",u:"5",forms:"+ Akkusativ"},
{id:246,a:"postquam",b:"nachdem",u:"13"},
{id:247,a:"prae",b:"vor",u:"6",forms:"+ Ablativ"},
{id:248,a:"praesens",b:"anwesend, gegenwärtig",u:"13",forms:"praesens f., praesens n. (Gen. praesentis)",loan:"der Präsenzdienst"},
{id:249,a:"primo",b:"zuerst",u:"4"},
{id:250,a:"primus",b:"der erste",u:"4",forms:"prima f., primum n.",loan:"prima"},
{id:251,a:"pro",b:"für",u:"6",forms:"+ Ablativ",loan:"pro und contra"},
{id:252,a:"publicus",b:"öffentlich",u:"12",forms:"publica f., publicum n.",loan:"das Publikum"},
{id:253,a:"puella",b:"das Mädchen",u:"3",forms:"puellae"},
{id:254,a:"puer",b:"der Bub",u:"3",forms:"pueri"},
{id:255,a:"pulcher",b:"schön",u:"5",forms:"pulchra f., pulchrum n."},
{id:256,a:"putare",b:"glauben, meinen, halten",u:"14",forms:"puto, putavi, putatum (+ dopp. Akk.)",loan:"der Computer, die Reputation"},
{id:257,a:"puto te socium",b:"ich halte dich für einen Freund",u:"14"},
{id:258,a:"quaerere",b:"suchen, jmdn. fragen",u:"14",forms:"quaero, quaesivi, quaesitum (ex + Abl.)",loan:"exquisit"},
{id:259,a:"quaero ex te",b:"ich frage dich",u:"14"},
{id:260,a:"quando",b:"wann",u:"9"},
{id:261,a:"qui",b:"welcher, welche, welches; der, die, das",u:"12",forms:"quae f., quod n. (Gen. cuius)"},
{id:262,a:"quidam",b:"ein (gewisser), ein bestimmter; Pl. einige",u:"12",forms:"quaedam f., quoddam n. (Gen. cuiusdam)"},
{id:263,a:"quies",b:"die Ruhe",u:"15",forms:"quietis",loan:"engl. quiet"},
{id:264,a:"quietus",b:"ruhig",u:"15",forms:"quieta f., quietum n."},
{id:265,a:"quis",b:"wer? was?",u:"8",forms:"quid n. (Gen. cuius)",loan:"das Quiz"},
{id:266,a:"quomodo",b:"wie",u:"7"},
{id:267,a:"quod",b:"dass, weil",u:"3"},
{id:268,a:"rana",b:"der Frosch",u:"1",forms:"ranae"},
{id:269,a:"recitare",b:"vorlesen",u:"7",forms:"recito, recitavi, recitatum",loan:"rezitieren"},
{id:270,a:"regere",b:"regieren, herrschen",u:"7",forms:"rego, rexi, rectum",loan:"der Regent, die Regie, das Regime"},
{id:271,a:"regina",b:"die Königin",u:"7",forms:"reginae",loan:"Vorname Regina"},
{id:272,a:"regnare",b:"regieren, herrschen",u:"7",forms:"regno, regnavi, regnatum"},
{id:273,a:"regnum",b:"das Königreich, die Herrschaft",u:"7",forms:"regni",loan:"das Regime, die Regie, die Regel, das Regal"},
{id:274,a:"res",b:"die Sache",u:"9",forms:"rei",loan:"real"},
{id:275,a:"res publica",b:"der Staat (öffentliche Sache)",u:"12",forms:"rei publicae",loan:"die Republik"},
{id:276,a:"respondere",b:"antworten",u:"1",forms:"respondeo, respondi, responsum",loan:"die Korrespondenz"},
{id:277,a:"rex",b:"der König",u:"7",forms:"regis",loan:"der Regent"},
{id:278,a:"ridere",b:"lachen",u:"12",forms:"rideo, risi, risum",loan:"engl. ridiculous"},
{id:279,a:"Romanus",b:"römisch",u:"11",forms:"Romana f., Romanum n."},
{id:280,a:"saepe",b:"oft",u:"11"},
{id:281,a:"salve, salvete",b:"hallo, guten Tag",u:"7"},
{id:282,a:"sanctus",b:"heilig",u:"8",forms:"sancta f., sanctum n.",loan:"St. (Sankt)"},
{id:283,a:"sanus",b:"gesund",u:"7",forms:"sana f., sanum n.",loan:"sanieren"},
{id:284,a:"satis",b:"genug",u:"15",loan:"die Satisfaktion"},
{id:285,a:"scire",b:"wissen, können, sich verstehen auf",u:"7",forms:"scio, scivi, scitum",loan:"engl. science"},
{id:286,a:"scribere",b:"schreiben",u:"10",forms:"scribo, scripsi, scriptum",loan:"das Manuskript"},
{id:287,a:"se",b:"sich",u:"5"},
{id:288,a:"sed",b:"aber, sondern",u:"6"},
{id:289,a:"semper",b:"immer",u:"3"},
{id:290,a:"senex",b:"alter Mann",u:"7",forms:"senis",loan:"senil"},
{id:291,a:"servare",b:"retten, bewahren",u:"14",forms:"servo, servavi, servatum",loan:"die Konserve"},
{id:292,a:"servus",b:"der Sklave, der Diener",u:"3",forms:"servi",loan:"„Servus!“, engl. servant"},
{id:293,a:"si",b:"wenn, ob",u:"13"},
{id:294,a:"simul",b:"gleichzeitig",u:"14",loan:"simultan"},
{id:295,a:"sine",b:"ohne",u:"6",forms:"+ Ablativ"},
{id:296,a:"socius",b:"der Freund, der Gefährte, der Kamerad",u:"14",forms:"socii",loan:"sozial"},
{id:297,a:"sol",b:"die Sonne",u:"13",forms:"solis",loan:"das Solarium, Solar-"},
{id:298,a:"solus",b:"allein",u:"8",forms:"sola f., solum n. (Gen. solius, Dat. soli)",loan:"das Solo, der Solist / die Solistin"},
{id:299,a:"solum",b:"nur",u:"8"},
{id:300,a:"spectaculum",b:"das Schauspiel",u:"15",forms:"spectaculi",loan:"das Spektakel"},
{id:301,a:"spectare",b:"anschauen, betrachten",u:"14",forms:"specto, spectavi, spectatum",loan:"der Inspektor / die Inspektorin"},
{id:302,a:"stare",b:"stehen",u:"2",forms:"sto, steti, statum",loan:"die Statue"},
{id:303,a:"studium",b:"der Eifer, das Streben, der Einsatz, die wissenschaftliche Beschäftigung",u:"6",forms:"studii",loan:"das Studium"},
{id:304,a:"stupidus",b:"dumm",u:"3",forms:"stupida f., stupidum n.",loan:"engl. stupid"},
{id:305,a:"sub (+ Akkusativ)",b:"unter",u:"6",forms:"+ Akkusativ",loan:"engl. submarine"},
{id:306,a:"sub (+ Ablativ)",b:"unter",u:"6",forms:"+ Ablativ",loan:"der Substandard"},
{id:307,a:"summus",b:"der oberste, höchste, größte",u:"6",forms:"summa f., summum n.",loan:"die Summe"},
{id:308,a:"suus",b:"sein, ihr",u:"5",forms:"sua f., suum n."},
{id:309,a:"tam ... quam",b:"so ... wie",u:"1"},
{id:310,a:"tamen",b:"dennoch, trotzdem",u:"10"},
{id:311,a:"tandem",b:"endlich",u:"6"},
{id:312,a:"taurus",b:"der Stier, der Ochse",u:"3",forms:"tauri",loan:"der Minotaurus"},
{id:313,a:"te",b:"dich",u:"2"},
{id:314,a:"a te",b:"von dir",u:"2"},
{id:315,a:"templum",b:"der Tempel",u:"6",forms:"templi"},
{id:316,a:"tempus",b:"die Zeit",u:"10",forms:"temporis",loan:"temporär"},
{id:317,a:"tenere",b:"halten, einhalten",u:"13",forms:"teneo, tenui, tentum",loan:"der Kontinent, der Container"},
{id:318,a:"terra",b:"die Erde",u:"5",forms:"terrae",loan:"die Terrasse, das Terrarium"},
{id:319,a:"timere",b:"fürchten, Angst haben",u:"5",forms:"timeo, timui",loan:"engl. timid"},
{id:320,a:"totus",b:"ganz",u:"6",forms:"tota f., totum n. (Gen. totius, Dat. toti)",loan:"total"},
{id:321,a:"trahere",b:"ziehen, führen, schleppen",u:"7",forms:"traho, traxi, tractum",loan:"der Traktor"},
{id:322,a:"trans",b:"über ... hinüber",u:"5",forms:"+ Akkusativ",loan:"der Transport"},
{id:323,a:"tu",b:"du",u:"3"},
{id:324,a:"tum",b:"dann",u:"11"},
{id:325,a:"tuus",b:"dein",u:"3",forms:"tua f., tuum n."},
{id:326,a:"ubi",b:"sobald; wo",u:"7"},
{id:327,a:"ultimus",b:"der letzte",u:"7",forms:"ultima f., ultimum n.",loan:"das Ultimatum"},
{id:328,a:"urbs",b:"die Stadt",u:"9",forms:"urbis",loan:"urban, engl. suburbs"},
{id:329,a:"uxor",b:"die Ehefrau",u:"13",forms:"uxoris"},
{id:330,a:"vacuus",b:"leer",u:"10",forms:"vacua f., vacuum n.",loan:"das Vakuum"},
{id:331,a:"vale, valete",b:"tschau, auf Wiedersehen, leb/lebt wohl",u:"7"},
{id:332,a:"vehemens",b:"heftig, intensiv",u:"13",forms:"vehemens f., vehemens n. (Gen. vehementis)",loan:"vehement"},
{id:333,a:"venire",b:"kommen",u:"2",forms:"venio, veni, ventum",loan:"der Advent"},
{id:334,a:"verbum",b:"das Wort, das Zeitwort",u:"6",forms:"verbi",loan:"das Verb"},
{id:335,a:"via",b:"die Straße",u:"13",forms:"viae",loan:"das Viadukt"},
{id:336,a:"videre",b:"sehen",u:"3",forms:"video, vidi, visum",loan:"die Vision, das Visum"},
{id:337,a:"villa",b:"das Landhaus, die Villa",u:"6",forms:"villae"},
{id:338,a:"vinum",b:"der Wein",u:"4",forms:"vini",loan:"die Vinothek"},
{id:339,a:"vir",b:"der Mann",u:"3",forms:"viri",loan:"viril"},
{id:340,a:"virtus",b:"die Tugend, der Mut, die Tüchtigkeit",u:"9",forms:"virtutis",loan:"virtuell"},
{id:341,a:"vita",b:"das Leben",u:"6",forms:"vitae",loan:"vital, die Vitamine"},
{id:342,a:"vocare",b:"rufen, nennen",u:"4",forms:"voco, vocavi, vocatum",loan:"vokal, der Vokativ"},
{id:343,a:"vos",b:"ihr, euch",u:"14"},
{id:344,a:"vox",b:"die Stimme",u:"9",forms:"vocis",loan:"der Vokal"},
{id:345,a:"magna voce",b:"mit lauter Stimme, laut",u:"9"}
  ]
});
