/*
  Latin -> German vocabulary set — "Latein 3. Klasse".
  Source: Screenshots in screenshots/Latein 3/  (Modul1, Modul2, Modul3, ModulX).
  Entries are deduplicated by lemma: a word introduced in Modul 1 keeps u="1"
  even when reviewed in later modules.
  Fields:
    a      Latin lemma (used for the quiz)
    b      German meaning (used for the quiz)
    u      module: "1", "2", "3", "X"
    forms  optional: Spezialformen (display only)
    rel    optional: verwandte lat. Wörter (display only, 4th column)
    loan   optional: Fremdwörter / Lehnwörter (display only, 5th column)
  IMPORTANT: `id` values are stable — never renumber.
*/
(window.VOCAB_REGISTRY=window.VOCAB_REGISTRY||[]).push({
  id:"la3-de",
  name:"Latein 3. Klasse",
  langA:"Latein",
  langB:"Deutsch",
  flagA:"🏛️",
  flagB:"🇩🇪",
  stripArticlesOnB:true,
  stripArticlesOnA:false,
  vocab:[
// ── Modul 1 ──────────────────────────────────────────────
{id:1,a:"addere 3",b:"hinzufügen",u:"1",forms:"addo, addidi, additum",loan:"Addition"},
{id:2,a:"adversus m.",b:"unerfreulich, feindlich, entgegengesetzt",u:"1",forms:"adversa f., adversum n.",rel:"adversarius, adversari, res adversae",loan:"adversativ"},
{id:3,a:"aetas f.",b:"das Zeitalter, das Alter, die Generation",u:"1",forms:"aetatis"},
{id:4,a:"ait, aiunt",b:"er, sie, es sagt; sie sagen",u:"1"},
{id:5,a:"aperire 4",b:"öffnen",u:"1",forms:"aperio, aperui, apertum",loan:"aper, Aperitif"},
{id:6,a:"apparere 2",b:"erscheinen, sich zeigen, sichtbar werden",u:"1",forms:"appareo, apparui",loan:"engl. appear"},
{id:7,a:"ascendere 3",b:"hinaufsteigen",u:"1",forms:"ascendo, ascendi, ascensum",rel:"ascensus, ascensio, descendere",loan:"Aszendent"},
{id:8,a:"colligere 3",b:"sammeln",u:"1",forms:"colligo, collegi, collectum",rel:"legere",loan:"Kollektion, engl. to collect"},
{id:9,a:"cupido f.",b:"die Begierde, die Liebe, die Leiden",u:"1",forms:"cupidinis",rel:"cupere, cupiditas, cupidus",loan:"Cupido"},
{id:10,a:"custos m./f.",b:"der Wächter / die Wächterin",u:"1",forms:"custodis",rel:"custodire",loan:"Kustos/Kustodin, Küster/in"},
{id:11,a:"deficere 3M",b:"schwinden, schwach werden, ausgehen",u:"1",forms:"deficio, defeci, defectum",rel:"defectio, defectus",loan:"Defekt, Defizit"},
{id:12,a:"discere 3",b:"lernen",u:"1",forms:"disco, didici",rel:"disciplina, discipulus",loan:"Disziplin"},
{id:13,a:"dolor m.",b:"der Schmerz",u:"1",forms:"doloris",rel:"dolere",loan:"kondolieren, Kondolenz"},
{id:14,a:"etsi",b:"auch wenn",u:"1"},
{id:15,a:"exercitus m.",b:"das Heer",u:"1",forms:"exercitus",rel:"exercere, exercitatio",loan:"exerzieren"},
{id:16,a:"felix m.",b:"glücklich",u:"1",forms:"felix f., felix n. (Gen. felicis)",rel:"felicitas, infelix",loan:"Name: Felix"},
{id:17,a:"fidelis m.",b:"treu, fromm",u:"1",forms:"fidelis f., fidele n.",rel:"fides, fidus",loan:"fidel, engl. high fidelity"},
{id:18,a:"forte",b:"zufällig",u:"1",rel:"fortuna, fors, fortasse"},
{id:19,a:"fortuna f.",b:"das Schicksal, das Glück, die Glücksgöttin",u:"1",forms:"fortunae",rel:"fors, forte",loan:"Fortuna, engl. fortune"},
{id:20,a:"hostis m.",b:"der Feind",u:"1",forms:"hostis",rel:"hostilis",loan:"hostil"},
{id:21,a:"ingenium n.",b:"die Begabung, die Anlage, das Genie",u:"1",forms:"ingenii",rel:"gignere, genus",loan:"Genie, Ingenieur"},
{id:22,a:"iustitia f.",b:"die Gerechtigkeit",u:"1",forms:"iustitiae",rel:"iustus, ius, iudex, iudicare, iudicium",loan:"Justiz"},
{id:23,a:"litterae f.",b:"die Schriften",u:"1",forms:"litterarum",rel:"littera, literatura",loan:"Literatur"},
{id:24,a:"lumen n.",b:"das Licht, das Augenlicht, das Auge",u:"1",forms:"luminis",loan:"illuminieren"},
{id:25,a:"membrum n.",b:"der Körperteil, das Glied",u:"1",forms:"membri",rel:"membratim",loan:"engl. member"},
{id:26,a:"memoria f.",b:"die Erinnerung, das Gedächtnis",u:"1",forms:"memoriae",rel:"memor",loan:"Memoiren, Memory, memorieren"},
{id:27,a:"neglegere 3",b:"vernachlässigen, ignorieren",u:"1",forms:"neglego, neglexi, neglectum",loan:"Negligé"},
{id:28,a:"nominare 1",b:"nennen",u:"1",forms:"nomino, nominavi, nominatum",rel:"nomen",loan:"nominieren"},
{id:29,a:"nonnulli m.",b:"einige (nicht keine)",u:"1",forms:"nonnullae f., nonnulla n.",rel:"non, nullus",loan:"Null"},
{id:30,a:"nubere 3",b:"heiraten (von der Frau aus gesehen)",u:"1",forms:"nubo, nupsi; + Dativ",rel:"nuptiae, nupta",loan:"Oper: Le nozze di Figaro"},
{id:31,a:"occupare 1",b:"besetzen, beschäftigen",u:"1",forms:"occupo, occupavi, occupatum",rel:"occupatio",loan:"okkupieren"},
{id:32,a:"odisse",b:"hassen",u:"1",forms:"odi",rel:"odium, odiosus"},
{id:33,a:"par m.",b:"gleich",u:"1",forms:"par f., par n.",loan:"Parität, Paar"},
{id:34,a:"parentes m.",b:"die Eltern",u:"1",forms:"parentium",rel:"parere, partus",loan:"engl. parents"},
{id:35,a:"parere 3M",b:"gebären",u:"1",forms:"pario, peperi, partum",rel:"partus, parentes",loan:"Partus, postpartal, engl. parents"},
{id:36,a:"porta f.",b:"die Tür",u:"1",forms:"portae",loan:"Pforte, Portal"},
{id:37,a:"potiri 4",b:"sich einer Sache bemächtigen",u:"1",forms:"potior, potitus sum + Abl.",rel:"potentia, potestas, potens",loan:"potent, Potenz, Potenzial"},
{id:38,a:"proficisci (Dep.)",b:"aufbrechen, sich auf den Weg machen",u:"1",forms:"proficiscor, profectus sum",rel:"profecto, profectio, profectus"},
{id:39,a:"prohibere 2",b:"behindern, verhindern, abhalten",u:"1",forms:"prohibeo, prohibui, prohibitum",loan:"Prohibition, Prohibitiv"},
{id:40,a:"promittere 3",b:"versprechen",u:"1",forms:"promitto, promisi, promissum",rel:"mittere",loan:"to promise"},
{id:41,a:"quidem / ne ... quidem",b:"jedenfalls, zwar / nicht einmal",u:"1"},
{id:42,a:"sapientia f.",b:"die Weisheit",u:"1",forms:"sapientiae",rel:"sapere, sapiens",loan:"Homo sapiens"},
{id:43,a:"scelus n.",b:"das Verbrechen",u:"1",forms:"sceleris",rel:"sceleratus, scelestus"},
{id:44,a:"senex m.",b:"alter Mann; alt, bejahrt, greis",u:"1",forms:"senis, senex f., senex n.",rel:"senescere, senectus",loan:"senil, senilis"},
{id:45,a:"spes f.",b:"die Hoffnung",u:"1",forms:"spei",rel:"sperare"},
{id:46,a:"tamquam",b:"wie wenn, als ob",u:"1"},
{id:47,a:"tradere 3",b:"weitergeben, überliefern",u:"1",forms:"trado, tradidi, traditum",rel:"traditio, traditor",loan:"Tradition, tradieren"},
{id:48,a:"tutus m.",b:"sicher",u:"1",forms:"tuta f., tutum n.",rel:"tueri, tutor, tutela",loan:"Tutorium, Tutor"},
{id:49,a:"uti",b:"gebrauchen, benutzen",u:"1",forms:"utor, usus sum + Ablativ",rel:"usus, utilis",loan:"Utensilien, Usus, engl. to use, useful"},
{id:50,a:"vero",b:"aber",u:"1"},
{id:51,a:"vertere 3",b:"drehen, wenden",u:"1",forms:"verto, verti, versum",rel:"verti, versus",loan:"Version, versus"},
{id:52,a:"vestis f.",b:"das Kleid, das Gewand",u:"1",forms:"vestis",rel:"vestibulum, vestimentum, investire",loan:"Weste, investieren, Vestibül, Investitur"},
{id:53,a:"vetus m.",b:"alt",u:"1",forms:"vetus f., vetus n. (Gen. veteris)",rel:"vetustas, veteranus, vetustus",loan:"Veteran"},
{id:54,a:"vulnus n.",b:"die Wunde",u:"1",forms:"vulneris",rel:"vulnerare, vulnerabilis",loan:"vulnerabel"},
// ── Modul 2 (neue Einträge, Review-Wörter aus Modul 1 weggelassen) ──
{id:55,a:"aeternus m.",b:"ewig, unendlich",u:"2",forms:"aeterna f., aeternum n.",rel:"aeternitas",loan:"engl. eternity"},
{id:56,a:"altus m.",b:"hoch, tief",u:"2",forms:"alta f., altum n.",rel:"altitudo",loan:"Altstimme"},
{id:57,a:"aptus m.",b:"passend, geeignet",u:"2",forms:"apta f., aptum n.",rel:"adaptare",loan:"adaptieren, Adaptor"},
{id:58,a:"armare 1",b:"bewaffnen",u:"2",forms:"armo, armavi, armatum",rel:"arma",loan:"Armatur, Armee"},
{id:59,a:"augere 2",b:"vergrößern, vermehren",u:"2",forms:"augeo, auxi, auctum",rel:"auctio",loan:"Auktion"},
{id:60,a:"cadere 3",b:"fallen",u:"2",forms:"cado, cecidi, casurus",rel:"casus",loan:"Kadenz, Kasus"},
{id:61,a:"cedere 3",b:"gehen, weichen",u:"2",forms:"cedo, cessi, cessum",loan:"Rezession, Konzession"},
{id:62,a:"cingere 3",b:"umgeben, umzingeln",u:"2",forms:"cingo, cinxi, cinctum",rel:"cingulum",loan:"umzingeln, Zingulum"},
{id:63,a:"comitari 1, Dep.",b:"begleiten",u:"2",forms:"comitor, comitatus sum",rel:"comes, comitatus",loan:"it. conte, franz. comte, comtesse"},
{id:64,a:"conditio f.",b:"die Bedingung, der Vorschlag, die Lage",u:"2",forms:"conditionis",rel:"condicere",loan:"Kondition"},
{id:65,a:"consuetudo f.",b:"die Gewohnheit, die Sitte, der Umgang",u:"2",forms:"consuetudinis",rel:"consuescere, consuetus"},
{id:66,a:"converti 3, Dep.",b:"sich bekehren, sich wenden",u:"2",forms:"convertor, conversus sum",loan:"Konversion"},
{id:67,a:"dignus m.",b:"würdig",u:"2",forms:"digna f., dignum n. + Abl.",rel:"dignitas, indignus",loan:"Dignität, indignieren"},
{id:68,a:"diu",b:"lang",u:"2",rel:"diuturnus"},
{id:69,a:"dolus m.",b:"die List, der Betrug",u:"2",forms:"doli",loan:"dolos"},
{id:70,a:"egredi 3M, Dep.",b:"hinausgehen",u:"2",forms:"egredior, egressus sum",rel:"gressus, gradi",loan:"aggressiv, Kongress"},
{id:71,a:"exitus m.",b:"das Ende, der Ausgang, der Tod",u:"2",forms:"exitus",rel:"exire",loan:"Exit, Exitus"},
{id:72,a:"experiri 4, Dep.",b:"erforschen, erproben, erleben",u:"2",forms:"experior, expertus sum",rel:"experimentum, expers",loan:"Experte, Experiment"},
{id:73,a:"exstruere 3 / construere",b:"errichten, bauen, konstruieren",u:"2",forms:"exstruo, exstruxi, exstructum",rel:"constructio",loan:"Konstruktion, destruktiv"},
{id:74,a:"fieri",b:"gemacht werden, werden, entstehen",u:"2",forms:"fio, factus sum",loan:"Fakt"},
{id:75,a:"firmus m.",b:"fest, stark, sicher",u:"2",forms:"firma f., firmum n.",rel:"firmare, firmamentum",loan:"Firmung, Konfirmation, Firmament"},
{id:76,a:"genus n.",b:"die Art, die Gattung",u:"2",forms:"generis",rel:"gignere",loan:"Generation"},
{id:77,a:"interesse / interest",b:"dazwischen sein, teilnehmen, dabei sein, es besteht ein Unterschied, es ist wichtig",u:"2",forms:"intersum, interfui",loan:"Interesse, interessant"},
{id:78,a:"intueri 2, Dep.",b:"betrachten, hinschauen",u:"2",forms:"intueor, intuitus sum",rel:"tueri, intuitus",loan:"Intuition, intuitiv"},
{id:79,a:"iuvenis",b:"der Mann, junger Mann",u:"2",forms:"iuvenis m.",rel:"iuvenalis, iuvenculus",loan:"juvenil"},
{id:80,a:"meminisse",b:"sich erinnern",u:"2",forms:"meminisse",rel:"memor, memoria",loan:"memorieren, memory, Memoiren"},
{id:81,a:"memor m.",b:"in Erinnerung, sich erinnernd an",u:"2",forms:"memor f., memor n. + Gen.",rel:"memoria, memorare",loan:"Memoiren, engl. memory"},
{id:82,a:"mox",b:"bald",u:"2"},
{id:83,a:"oblivisci 3, Dep.",b:"vergessen",u:"2",forms:"obliviscor, oblitus sum + Gen.",rel:"oblivio"},
{id:84,a:"ornare 1",b:"schmücken, verzieren",u:"2",forms:"orno, ornavi, ornatum",rel:"ornamentum",loan:"Ornat, Ornament"},
{id:85,a:"pars f.",b:"der Teil, der Abschnitt",u:"2",forms:"partis",rel:"partim, partire",loan:"Partei, partiell"},
{id:86,a:"permittere 3",b:"erlauben",u:"2",forms:"permitto, permisi, permissum",loan:"permissiv, engl. permit, permission"},
{id:87,a:"pons m.",b:"die Brücke",u:"2",forms:"pontis",loan:"Pontifex"},
{id:88,a:"posteritas f.",b:"die Nachwelt",u:"2",forms:"posteritatis",rel:"post, posterior, posteri"},
{id:89,a:"praecipere 3M",b:"vorschreiben, befehlen",u:"2",forms:"praecipio, praecepi, praeceptum",rel:"praeceptum, praeceptio",loan:"Präzeption"},
{id:90,a:"pugnare 1",b:"kämpfen",u:"2",forms:"pugno, pugnavi, pugnatum",rel:"pugna, oppugnare"},
{id:91,a:"quamvis",b:"wenn auch, obwohl",u:"2"},
{id:92,a:"reverti 3, Semidep.",b:"zurückkehren",u:"2",forms:"revertor, reverti, reversum",rel:"reversio",loan:"reversieren"},
{id:93,a:"rogare 1",b:"fragen, bitten",u:"2",forms:"rogo, rogavi, rogatum",rel:"interrogare, rogitare",loan:"derogieren, abrogieren, Interrogativpronomen"},
{id:94,a:"salus f.",b:"das Heil, das Wohl, die Rettung, der Gruß",u:"2",forms:"salutis",rel:"salutare",loan:"salutieren, Salut, S.P.A. (salus per aquam)"},
{id:95,a:"sententia f.",b:"die Meinung, der Lehrsatz, das Urteil",u:"2",forms:"sententiae",loan:"Sentenz, engl. sentence"},
{id:96,a:"servire 4",b:"dienen",u:"2",forms:"servio, servivi, servitum",rel:"servus, servitus",loan:"servieren, Serviette, Service"},
{id:97,a:"tacere 2",b:"schweigen",u:"2",forms:"taceo, tacui, tacitum",rel:"tacitus"},
{id:98,a:"tantus m.",b:"so groß",u:"2",forms:"tanta f., tantum n.",rel:"tantum",loan:"Tantiemen"},
{id:99,a:"tristis m.",b:"traurig",u:"2",forms:"tristis f., triste n. (Gen. tristis)",rel:"tristitia",loan:"trist"},
{id:100,a:"turba f.",b:"die Schar, das Getümmel, das Gedränge, der Wirbel",u:"2",forms:"turbae",rel:"turbare, turbulentus",loan:"turbulent"},
{id:101,a:"vadere 3",b:"gehen",u:"2",forms:"vado",rel:"invadere",loan:"Vademecum, Invasion"},
{id:102,a:"vereri 2, Dep.",b:"sich scheuen, sich fürchten",u:"2",forms:"vereor, veritus sum",rel:"reverentia",loan:"Reverenz"},
{id:103,a:"veritas f.",b:"die Wahrheit",u:"2",forms:"veritatis",rel:"verus, verisimilis",loan:"verifizieren, Vera (Name)"},
// ── Modul 3 (neue Einträge) ────────────────────────────────
{id:104,a:"adorir 4, Dep.",b:"angreifen",u:"3",forms:"adorior, adortus sum",rel:"oriri"},
{id:105,a:"affectus m.",b:"die Leidenschaft, der Affekt",u:"3",forms:"affectus",rel:"afficere, affectare, affectio",loan:"affektiert, Affekt"},
{id:106,a:"aliqui m.",b:"irgendein, irgendeine, irgendein",u:"3",forms:"aliqua f., aliquod n. (Gen. alicuius)"},
{id:107,a:"animadvertere 3",b:"bemerken",u:"3",forms:"animadverto, animadverti, animadversum",rel:"anima, vertere"},
{id:108,a:"atque",b:"und; bei Vergleichen: wie",u:"3"},
{id:109,a:"auctoritas f.",b:"der Einfluss, das Ansehen",u:"3",forms:"auctoritatis",rel:"auctor, augere",loan:"Autorität"},
{id:110,a:"audere 2, Semidep.",b:"wagen",u:"3",forms:"audeo, ausus sum",rel:"audacia, audax"},
{id:111,a:"brevis m.",b:"kurz",u:"3",forms:"brevis f., breve n. (Gen. brevis)",rel:"brevitas, breviarium",loan:"Brief, Brevier"},
{id:112,a:"censere 2",b:"beurteilen, einschätzen",u:"3",forms:"censeo, censui",rel:"census",loan:"Zensur"},
{id:113,a:"communis m.",b:"gemeinsam",u:"3",forms:"communis f., commune n.",rel:"communicare",loan:"Kommune, kommunizieren, engl. common, community"},
{id:114,a:"contendere 3",b:"anspannen, eilen, kämpfen",u:"3",forms:"contendo, contendi, contentum",rel:"contentio",loan:"engl. contention, contest"},
{id:115,a:"cor n.",b:"das Herz",u:"3",forms:"cordis",rel:"discordia, concordia, cordialis",loan:"akkordieren, Akkord, Courage"},
{id:116,a:"corrumpere 3",b:"verderben, bestechen",u:"3",forms:"corrumpo, corrupi, corruptum",rel:"rumpere",loan:"korrupt, Korruption, korrumpieren"},
{id:117,a:"defendere 3",b:"verteidigen, abwehren",u:"3",forms:"defendo, defendi, defensum",rel:"defensio",loan:"Defensive"},
{id:118,a:"differre",b:"aufschieben, sich unterscheiden",u:"3",forms:"differo, distuli, dilatum",loan:"Differenz"},
{id:119,a:"diligens m.",b:"sorgfältig, umsichtig",u:"3",forms:"diligens f., diligens n. (Gen. diligentis)",rel:"diligentia",loan:"engl. diligent"},
{id:120,a:"discrimen n.",b:"der Unterschied, die Gefahr",u:"3",forms:"discriminis",rel:"discernere, discriminare",loan:"diskriminieren, Diskriminante"},
{id:121,a:"dividere 3",b:"teilen",u:"3",forms:"divido, divisi, divisum",rel:"divisio",loan:"Division, Dividend, Divisor"},
{id:122,a:"errare 1",b:"irren",u:"3",forms:"erro, erravi, erratum",rel:"error",loan:"engl. error"},
{id:123,a:"extremus m.",b:"der letzte, der äußerste, der entfernteste",u:"3",forms:"extrema f., extremum n.",rel:"extra",loan:"extrem"},
{id:124,a:"facinus n.",b:"die Tat, die Untat, das Verbrechen",u:"3",forms:"facinoris",rel:"facere, fas, nefas, facilis"},
{id:125,a:"ignorare 1",b:"nicht wissen",u:"3",forms:"ignoro, ignoravi, ignoratum",rel:"ignorantia",loan:"ignorant, Ignoranz"},
{id:126,a:"imago f.",b:"das Bild, das Abbild",u:"3",forms:"imaginis",rel:"imaginari",loan:"Image, imaginär"},
{id:127,a:"incedere 3",b:"gehen",u:"3",forms:"incedo, incessi, incessum",rel:"cedere, processus, accessus",loan:"Konzession, Prozess, exzessiv"},
{id:128,a:"initium n.",b:"der Anfang",u:"3",forms:"initii",rel:"inire",loan:"Initiale, Initiative"},
{id:129,a:"interficere 3M",b:"töten",u:"3",forms:"interficio, interfeci, interfectum"},
{id:130,a:"invadere 3",b:"eindringen",u:"3",forms:"invado, invasi, invasum",rel:"evadere",loan:"Invasion"},
{id:131,a:"maritus m.",b:"der Ehemann, der Gatte",u:"3",forms:"mariti"},
{id:132,a:"metus m.",b:"die Angst",u:"3",forms:"metus",rel:"metuere"},
{id:133,a:"negotium n.",b:"die Arbeit, die Aufgabe, der Auftrag",u:"3",forms:"negotii",rel:"otium",loan:"engl. negotiate"},
{id:134,a:"numquam",b:"niemals",u:"3"},
{id:135,a:"occultare 1",b:"verstecken, verbergen",u:"3",forms:"occulto, occultavi, occultatum",rel:"occultus, occultatio",loan:"okkult, Okkultismus"},
{id:136,a:"officium n.",b:"die Aufgabe, die Pflicht, das Amt",u:"3",forms:"officii",rel:"officina, officinalis",loan:"offiziell, engl. office"},
{id:137,a:"pariter",b:"in gleicher Weise",u:"3",rel:"par",loan:"Parität, Paar"},
{id:138,a:"pauper m.",b:"arm",u:"3",forms:"pauper f., pauper n. (Gen. pauperis)",rel:"paupertas"},
{id:139,a:"pellere 3 / repellere 3",b:"treiben / zurücktreiben, vertreiben",u:"3",forms:"pello, pepuli, pulsum / repello, repuli, repulsum",rel:"pulsus",loan:"Propeller, Puls, pulsieren, Impuls"},
{id:140,a:"poena f.",b:"die Strafe",u:"3",forms:"poenae",loan:"Pönale"},
{id:141,a:"posterus m.",b:"der nächste, der folgende",u:"3",forms:"postera f., posterum n.",rel:"post, postea, posteritas"},
{id:142,a:"praeter + Akk.",b:"außer",u:"3",loan:"Präteritum"},
{id:143,a:"propellere 3",b:"vorantreiben, wegtreiben, forttreiben, vertreiben",u:"3",forms:"propello, propuli, propulsum",rel:"pellere, pulsus",loan:"Propeller, Puls"},
{id:144,a:"pudicitia f.",b:"die Tugend, der Anstand",u:"3",forms:"pudicitiae",rel:"pudor, pudet"},
{id:145,a:"quia",b:"weil",u:"3"},
{id:146,a:"ratio f.",b:"die Vernunft, die Überlegung, die Methode, der Grund, das Argument, die Berechnung",u:"3",forms:"rationis",loan:"rational, rationell"},
{id:147,a:"scilicet",b:"natürlich, selbstverständlich",u:"3"},
{id:148,a:"simplex m.",b:"einfach, schlicht",u:"3",forms:"simplex f., simplex n. (Gen. simplicis)",rel:"simplicitas",loan:"simpel"},
{id:149,a:"statuere 3",b:"aufstellen, festsetzen, beschließen",u:"3",forms:"statuo, statui, statutum",rel:"statua, statio, statutum, status, statura",loan:"Statut, Station, Statue, Statur, Status"},
{id:150,a:"succedere 3 / cedere 3",b:"nachfolgen / gehen, weichen",u:"3",forms:"succedo, successi, successum / cessi, cessum",rel:"successus, successio, successor",loan:"engl. success"},
{id:151,a:"tegere 3",b:"bedecken, schützen",u:"3",forms:"tego, texi, tectum",rel:"tectum",loan:"decken, Decke"},
{id:152,a:"ullus m.",b:"irgendein",u:"3",forms:"ulla f., ullum n. (Gen. ullius, Dat. ulli)",rel:"nullus",loan:"Null, annullieren"},
{id:153,a:"usus m.",b:"der Gebrauch, der Nutzen",u:"3",forms:"usus",rel:"uti, utilis",loan:"Usus, engl. use"},
{id:154,a:"uterque m.",b:"jeder von beiden, beide",u:"3",forms:"utraque f., utrumque n. (Gen. utriusque)"},
// ── Modul X (nur neue Einträge; Review-Wörter aus 1–3 weggelassen) ──
{id:155,a:"potentia f.",b:"die Macht, der Einfluss",u:"X",forms:"potentiae",rel:"posse, potens, potestas",loan:"Potenz, potent, Potenzial"}
]});
